/*
 Highcharts JS v9.3.2 (2021-12-20)

 Highcharts Drilldown module

 Author: Torstein Honsi
 License: www.highcharts.com/license

*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/drilldown",["highcharts"],function(t){a(t);a.Highcharts=t;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function t(a,w,h,q){a.hasOwnProperty(w)||(a[w]=q.apply(null,h))}a=a?a._modules:{};t(a,"Extensions/Breadcrumbs.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/DefaultOptions.js"],a["Core/Utilities.js"],
a["Core/FormatUtilities.js"]],function(a,w,h,q,m){var t=m.format;m=q.addEvent;var A=q.objectEach,D=q.extend,x=q.fireEvent,y=q.merge,v=q.pick,E=q.defined;D(h.defaultOptions.lang,{mainBreadcrumb:"Main"});h=function(){function a(b,c){this.group=void 0;this.list=[];this.elementList={};this.isDirty=!0;this.level=0;this.options=void 0;c=y(b.options.drilldown&&b.options.drilldown.drillUpButton,a.defaultBreadcrumbsOptions,c);this.chart=b;this.options=c||{}}a.prototype.updateProperties=function(b){this.setList(b);
this.setLevel();this.isDirty=!0};a.prototype.setList=function(b){this.list=b};a.prototype.setLevel=function(){this.level=this.list.length&&this.list.length-1};a.prototype.getLevel=function(){return this.level};a.prototype.getButtonText=function(b){var a=this.chart,k=this.options,e=a.options.lang,h=v(k.format,k.showFullPath?"{level.name}":"\u2190 {level.name}");e=e&&v(e.drillUpText,e.mainBreadcrumb);b=k.formatter&&k.formatter(b)||t(h,{level:b.levelOptions},a)||"";"\u2190 "===b&&E(e)&&(b=k.showFullPath?
e:"\u2190 "+e);return b};a.prototype.redraw=function(){this.isDirty&&this.render();this.group&&this.group.align();this.isDirty=!1};a.prototype.render=function(){var a=this.chart,c=this.options;!this.group&&c&&(this.group=a.renderer.g("breadcrumbs-group").addClass("highcharts-no-tooltip highcharts-breadcrumbs").attr({zIndex:c.zIndex}).add());c.showFullPath?this.renderFullPathButtons():this.renderSingleButton();this.alignBreadcrumbsGroup()};a.prototype.renderFullPathButtons=function(){this.destroySingleButton();
this.resetElementListState();this.updateListElements();this.destroyListElements()};a.prototype.renderSingleButton=function(){var a=this.chart,c=this.list,k=this.options.buttonSpacing;this.destroyListElements();var e=this.group?this.group.getBBox().width:k;c=c[c.length-2];!a.drillUpButton&&0<this.level?a.drillUpButton=this.renderButton(c,e,k):a.drillUpButton&&(0<this.level?this.updateSingleButton():this.destroySingleButton())};a.prototype.alignBreadcrumbsGroup=function(a){if(this.group){var b=this.options,
k=b.buttonTheme,e=b.position,h="chart"===b.relativeTo||"spacingBox"===b.relativeTo?void 0:"scrollablePlotBox",f=this.group.getBBox();b=2*(k.padding||0)+b.buttonSpacing;e.width=f.width+b;e.height=f.height+b;e=y(e);a&&(e.x+=a);e.y=v(e.y,this.yOffset,0);this.group.align(e,!0,h)}};a.prototype.renderButton=function(a,c,k){var b=this,h=this.chart,f=b.options,u=y(f.buttonTheme),p=u.states;delete u.states;c=h.renderer.button(b.getButtonText(a),c,k,function(c){var e=f.events&&f.events.click,k;e&&(k=e.call(b,
c,a));!1!==k&&(c.newLevel=f.showFullPath?a.level:b.level-1,x(b,"up",c))},u,p&&p.hover,p&&p.select,p&&p.disabled).addClass("highcharts-breadcrumbs-button").add(b.group);h.styledMode||c.attr(f.style);return c};a.prototype.renderSeparator=function(a,c){var b=this.chart,e=this.options.separator;a=b.renderer.label(e.text,a,c,void 0,void 0,void 0,!1).addClass("highcharts-breadcrumbs-separator").add(this.group);b.styledMode||a.css(e.style);return a};a.prototype.update=function(a){y(!0,this.options,a);this.destroy();
this.isDirty=!0};a.prototype.updateSingleButton=function(){var a=this.chart,c=this.list[this.level-1];a.drillUpButton&&a.drillUpButton.attr({text:this.getButtonText(c)})};a.prototype.destroy=function(){this.destroySingleButton();this.destroyListElements(!0);this.group&&this.group.destroy();this.group=void 0};a.prototype.destroyListElements=function(a){var b=this.elementList;A(b,function(c,e){if(a||!b[e].updated)c=b[e],c.button&&c.button.destroy(),c.separator&&c.separator.destroy(),delete c.button,
delete c.separator,delete b[e]});a&&(this.elementList={})};a.prototype.destroySingleButton=function(){this.chart.drillUpButton&&(this.chart.drillUpButton.destroy(),this.chart.drillUpButton=void 0)};a.prototype.resetElementListState=function(){A(this.elementList,function(a){a.updated=!1})};a.prototype.updateListElements=function(){var a=function(a,b){return a.getBBox().width+b},c=this,h=c.elementList,e=c.options.buttonSpacing,u=c.list,f=c.group?a(c.group,e):e,m;u.forEach(function(b,k){k=k===u.length-
1;if(h[b.level]){m=h[b.level];var p=m.button;m.separator||k?m.separator&&k&&(m.separator.destroy(),delete m.separator):(f+=e,m.separator=c.renderSeparator(f,e),f+=a(m.separator,e));h[b.level].updated=!0}else{p=c.renderButton(b,f,e);f+=a(p,e);if(!k){var q=c.renderSeparator(f,e);f+=a(q,e)}h[b.level]={button:p,separator:q,updated:!0}}p&&p.setState(k?2:0)})};a.defaultBreadcrumbsOptions={buttonTheme:{fill:"none",height:18,padding:2,"stroke-width":0,zIndex:7,states:{select:{fill:"none"}},style:{color:"#335cad"}},
buttonSpacing:5,floating:!1,format:void 0,relativeTo:"plotBox",position:{align:"left",verticalAlign:"top",x:0,y:void 0},separator:{text:"/",style:{color:"#666666"}},showFullPath:!0,style:{},useHTML:!1,zIndex:7};return a}();w.Breadcrumbs||(w.Breadcrumbs=h,m(a,"getMargins",function(){var a=this.breadcrumbs;if(a&&!a.options.floating&&a.level){var b=a.options,c=b.buttonTheme;c=(c.height||0)+2*(c.padding||0)+b.buttonSpacing;b=b.position.verticalAlign;"bottom"===b?(this.marginBottom=(this.marginBottom||
0)+c,a.yOffset=c):"middle"!==b?(this.plotTop+=c,a.yOffset=-c):a.yOffset=void 0}}),m(a,"redraw",function(){this.breadcrumbs&&this.breadcrumbs.redraw()}),m(a,"destroy",function(){this.breadcrumbs&&(this.breadcrumbs.destroy(),this.breadcrumbs=void 0)}),m(a,"afterShowResetZoom",function(){if(this.breadcrumbs){var a=this.resetZoomButton&&this.resetZoomButton.getBBox(),b=this.breadcrumbs.options;a&&"right"===b.position.align&&"plotBox"===b.relativeTo&&this.breadcrumbs.alignBreadcrumbsGroup(-a.width-b.buttonSpacing)}}),
m(a,"selection",function(a){!0===a.resetSelection&&this.breadcrumbs&&this.breadcrumbs.alignBreadcrumbsGroup()}));"";return h});t(a,"Extensions/Drilldown.js",[a["Core/Animation/AnimationUtilities.js"],a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Series/Column/ColumnSeries.js"],a["Core/FormatUtilities.js"],a["Core/Globals.js"],a["Core/DefaultOptions.js"],a["Core/Series/Point.js"],a["Core/Series/Series.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Renderer/SVG/SVGRenderer.js"],
a["Core/Axis/Tick.js"],a["Core/Utilities.js"],a["Extensions/Breadcrumbs.js"]],function(a,t,h,q,m,M,A,K,x,y,v,E,u,b,c){function k(a){var g=e(this.chart.options.drilldown.animation);a&&(a.hide(),G(function(){a&&a.added&&a.fadeIn()},Math.max(g.duration-50,0)))}var e=a.animObject,w=A.noop;a=K.defaultOptions;var f=b.addEvent,D=b.removeEvent,p=b.extend,z=b.fireEvent,B=b.merge,L=b.objectEach,C=b.pick,G=b.syncTimeout;v=v.seriesTypes.pie;var H=1;p(a.lang,{});a.drilldown={activeAxisLabelStyle:{cursor:"pointer",
color:"#003399",fontWeight:"bold",textDecoration:"underline"},activeDataLabelStyle:{cursor:"pointer",color:"#003399",fontWeight:"bold",textDecoration:"underline"},animation:{duration:500},drillUpButton:{position:{align:"right",x:-10,y:10}}};E.prototype.Element.prototype.fadeIn=function(a){this.attr({opacity:.1,visibility:"inherit"}).animate({opacity:C(this.newOpacity,1)},a||{duration:250})};h.prototype.addSeriesAsDrilldown=function(a,d){this.addSingleSeriesAsDrilldown(a,d);this.applyDrilldown()};
h.prototype.addSingleSeriesAsDrilldown=function(a,d){var g=a.series,l=g.xAxis,b=g.yAxis,c=[],e=[],n;var r=this.styledMode?{colorIndex:C(a.colorIndex,g.colorIndex)}:{color:a.color||g.color};this.drilldownLevels||(this.drilldownLevels=[]);var f=g.options._levelNumber||0;(n=this.drilldownLevels[this.drilldownLevels.length-1])&&n.levelNumber!==f&&(n=void 0);d=p(p({_ddSeriesId:H++},r),d);var h=g.points.indexOf(a);g.chart.series.forEach(function(a){a.xAxis!==l||a.isDrilling||(a.options._ddSeriesId=a.options._ddSeriesId||
H++,a.options._colorIndex=a.userOptions._colorIndex,a.options._levelNumber=a.options._levelNumber||f,n?(c=n.levelSeries,e=n.levelSeriesOptions):(c.push(a),a.purgedOptions=B({_ddSeriesId:a.options._ddSeriesId,_levelNumber:a.options._levelNumber,selected:a.options.selected},a.userOptions),e.push(a.purgedOptions)))});a=p({levelNumber:f,seriesOptions:g.options,seriesPurgedOptions:g.purgedOptions,levelSeriesOptions:e,levelSeries:c,shapeArgs:a.shapeArgs,bBox:a.graphic?a.graphic.getBBox():{},color:a.isNull?
q.parse(r.color).setOpacity(0).get():r.color,lowerSeriesOptions:d,pointOptions:g.options.data[h],pointIndex:h,oldExtremes:{xMin:l&&l.userMin,xMax:l&&l.userMax,yMin:b&&b.userMin,yMax:b&&b.userMax},resetZoomButton:this.resetZoomButton},r);this.drilldownLevels.push(a);l&&l.names&&(l.names.length=0);d=a.lowerSeries=this.addSeries(d,!1);d.options._levelNumber=f+1;l&&(l.oldPos=l.pos,l.userMin=l.userMax=null,b.userMin=b.userMax=null);g.type===d.type&&(d.animate=d.animateDrilldown||w,d.options.animation=
!0)};h.prototype.applyDrilldown=function(){var a=this.drilldownLevels;if(a&&0<a.length){var d=a[a.length-1].levelNumber;this.drilldownLevels.forEach(function(a){a.levelNumber===d&&a.levelSeries.forEach(function(a){a.options&&a.options._levelNumber===d&&a.remove(!1)})})}this.resetZoomButton&&(this.resetZoomButton.hide(),delete this.resetZoomButton);this.pointer.reset();z(this,"afterDrilldown");this.redraw();z(this,"afterApplyDrilldown")};var I=function(a){var d=[];if((a=a.drilldownLevels)&&a.length){d[0]||
d.push({level:0,levelOptions:a[0].seriesOptions});var g=d[d.length-1];a.forEach(function(a){a.levelNumber+1>g.level&&d.push({level:a.levelNumber+1,levelOptions:a.pointOptions})})}return d};h.prototype.drillUp=function(){if(this.drilldownLevels&&0!==this.drilldownLevels.length){z(this,"beforeDrillUp");for(var a=this,d=a.drilldownLevels,b=d[d.length-1].levelNumber,l=d.length,c=a.series,e,f,n,r,h=function(d){c.forEach(function(a){a.options._ddSeriesId===d._ddSeriesId&&(g=a)});var g=g||a.addSeries(d,
!1);g.type===n.type&&g.animateDrillupTo&&(g.animate=g.animateDrillupTo);d===f.seriesPurgedOptions&&(r=g)};l--;)if(f=d[l],f.levelNumber===b){d.pop();n=f.lowerSeries;if(!n.chart)for(e=c.length;e--;)if(c[e].options.id===f.lowerSeriesOptions.id&&c[e].options._levelNumber===b+1){n=c[e];break}n.xData=[];f.levelSeriesOptions.forEach(h);z(a,"drillup",{seriesOptions:f.seriesPurgedOptions||f.seriesOptions});this.resetZoomButton&&this.resetZoomButton.destroy();r.type===n.type&&(r.drilldownLevel=f,r.options.animation=
a.options.drilldown.animation,n.animateDrillupFrom&&n.chart&&n.animateDrillupFrom(f));r.options._levelNumber=b;n.remove(!1);r.xAxis&&(e=f.oldExtremes,r.xAxis.setExtremes(e.xMin,e.xMax,!1),r.yAxis.setExtremes(e.yMin,e.yMax,!1));f.resetZoomButton&&(a.resetZoomButton=f.resetZoomButton,a.resetZoomButton.show())}z(a,"afterDrillUp");this.redraw();this.ddDupes.length=[];z(a,"drillupall")}};f(h,"afterInit",function(){var a=this;a.drilldown={chart:a,fadeInGroup:k,update:function(d,g){B(!0,a.options.drilldown,
d);C(g,!0)&&a.redraw()}}});f(h,"render",function(){(this.xAxis||[]).forEach(function(a){a.ddPoints={};a.series.forEach(function(d){var b,g=d.xData||[],c=d.points;for(b=0;b<g.length;b++){var e=d.options.data[b];"number"!==typeof e&&(e=d.pointClass.prototype.optionsToObject.call({series:d},e),e.drilldown&&(a.ddPoints[g[b]]||(a.ddPoints[g[b]]=[]),e=b-(d.cropStart||0),a.ddPoints[g[b]].push(c&&0<=e&&e<c.length?c[e]:!0)))}});L(a.ticks,u.prototype.drillable)})});f(A.Breadcrumbs,"up",function(a){var d=this.chart;
a=this.getLevel()-a.newLevel;for(var b=0;b<a;b++)d.drillUp()});f(h,"afterDrilldown",function(){var a=this.options.drilldown;a=a&&a.breadcrumbs;this.breadcrumbs||(this.breadcrumbs=new c(this,a));this.breadcrumbs.updateProperties(I(this))});f(h,"afterDrillUp",function(){this.breadcrumbs&&this.breadcrumbs.updateProperties(I(this))});f(h,"update",function(a){var d=this.breadcrumbs,b=a.options.drilldown&&a.options.drilldown.breadcrumbs;d&&b&&d.update(a.options.drilldown.breadcrumbs)});m.prototype.animateDrillupTo=
function(a){if(!a){var d=this,b=d.drilldownLevel;this.points.forEach(function(a){var d=a.dataLabel;a.graphic&&a.graphic.hide();d&&(d.hidden="hidden"===d.attr("visibility"),d.hidden||(d.hide(),a.connector&&a.connector.hide()))});G(function(){if(d.points){var a=[];d.data.forEach(function(d){a.push(d)});d.nodes&&(a=a.concat(d.nodes));a.forEach(function(a,d){d=d===(b&&b.pointIndex)?"show":"fadeIn";var e="show"===d?!0:void 0,g=a.dataLabel;if(a.graphic)a.graphic[d](e);g&&!g.hidden&&(g.fadeIn(),a.connector&&
a.connector.fadeIn())})}},Math.max(this.chart.options.drilldown.animation.duration-50,0));delete this.animate}};m.prototype.animateDrilldown=function(a){var d=this,b=this.chart,g=b.drilldownLevels,c,f=e(b.options.drilldown.animation),h=this.xAxis,n=b.styledMode;a||(g.forEach(function(a){d.options._ddSeriesId===a.lowerSeriesOptions._ddSeriesId&&(c=a.shapeArgs,n||(c.fill=a.color))}),c.x+=C(h.oldPos,h.pos)-h.pos,this.points.forEach(function(a){var b=a.shapeArgs;n||(b.fill=a.color);a.graphic&&a.graphic.attr(c).animate(p(a.shapeArgs,
{fill:a.color||d.color}),f)}),b.drilldown&&b.drilldown.fadeInGroup(this.dataLabelsGroup),delete this.animate)};m.prototype.animateDrillupFrom=function(a){var d=e(this.chart.options.drilldown.animation),b=this.group,c=b!==this.chart.columnGroup,g=this;g.trackerGroups.forEach(function(a){if(g[a])g[a].on("mouseover")});c&&delete this.group;this.points.forEach(function(e){var f=e.graphic,l=a.shapeArgs,h=function(){f.destroy();b&&c&&(b=b.destroy())};f&&l&&(delete e.graphic,g.chart.styledMode||(l.fill=
a.color),d.duration?f.animate(l,B(d,{complete:h})):(f.attr(l),h()))})};v&&p(v.prototype,{animateDrillupTo:m.prototype.animateDrillupTo,animateDrillupFrom:m.prototype.animateDrillupFrom,animateDrilldown:function(a){var d=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],b=this.chart.options.drilldown.animation;this.is("item")&&(b.duration=0);if(this.center){var c=d.shapeArgs,e=c.start,g=(c.end-e)/this.points.length,f=this.chart.styledMode;a||(this.points.forEach(function(a,h){var l=a.shapeArgs;
f||(c.fill=d.color,l.fill=a.color);if(a.graphic)a.graphic.attr(B(c,{start:e+h*g,end:e+(h+1)*g}))[b?"animate":"attr"](l,b)}),this.chart.drilldown&&this.chart.drilldown.fadeInGroup(this.dataLabelsGroup),delete this.animate)}}});x.prototype.doDrilldown=function(){this.runDrilldown()};x.prototype.runDrilldown=function(a,d,b){var c=this.series.chart,e=c.options.drilldown,g=(e.series||[]).length;c.ddDupes||(c.ddDupes=[]);for(;g--&&!f;)if(e.series[g].id===this.drilldown&&-1===c.ddDupes.indexOf(this.drilldown)){var f=
e.series[g];c.ddDupes.push(this.drilldown)}z(c,"drilldown",{point:this,seriesOptions:f,category:d,originalEvent:b,points:"undefined"!==typeof d&&this.series.xAxis.getDDPoints(d).slice(0)},function(b){var d=b.point.series&&b.point.series.chart,c=b.seriesOptions;d&&c&&(a?d.addSingleSeriesAsDrilldown(b.point,c):d.addSeriesAsDrilldown(b.point,c))})};t.prototype.drilldownCategory=function(a,b){this.getDDPoints(a).forEach(function(d){d&&d.series&&d.series.visible&&d.runDrilldown&&d.runDrilldown(!0,a,b)});
this.chart.applyDrilldown()};t.prototype.getDDPoints=function(a){return this.ddPoints&&this.ddPoints[a]||[]};u.prototype.drillable=function(){var a=this.pos,b=this.label,c=this.axis,e="xAxis"===c.coll&&c.getDDPoints,h=e&&c.getDDPoints(a),k=c.chart.styledMode;e&&(b&&h&&h.length?(b.drillable=!0,b.basicStyles||k||(b.basicStyles=B(b.styles)),b.addClass("highcharts-drilldown-axis-label"),b.removeOnDrillableClick&&D(b.element,"click"),b.removeOnDrillableClick=f(b.element,"click",function(b){b.preventDefault();
c.drilldownCategory(a,b)}),k||b.css(c.chart.options.drilldown.activeAxisLabelStyle)):b&&b.drillable&&b.removeOnDrillableClick&&(k||(b.styles={},b.css(b.basicStyles)),b.removeOnDrillableClick(),b.removeClass("highcharts-drilldown-axis-label")))};f(x,"afterInit",function(){this.drilldown&&!this.unbindDrilldownClick&&(this.unbindDrilldownClick=f(this,"click",J));return this});f(x,"update",function(a){a=a.options||{};a.drilldown&&!this.unbindDrilldownClick?this.unbindDrilldownClick=f(this,"click",J):
!a.drilldown&&void 0!==a.drilldown&&this.unbindDrilldownClick&&(this.unbindDrilldownClick=this.unbindDrilldownClick())});var J=function(a){var b=this.series;b.xAxis&&!1===b.chart.options.drilldown.allowPointDrilldown?b.xAxis.drilldownCategory(this.x,a):this.runDrilldown(void 0,void 0,a)};f(y,"afterDrawDataLabels",function(){var a=this.chart.options.drilldown.activeDataLabelStyle,b=this.chart.renderer,c=this.chart.styledMode;this.points.forEach(function(d){var e=d.options.dataLabels,f=C(d.dlOptions,
e&&e.style,{});d.drilldown&&d.dataLabel&&("contrast"!==a.color||c||(f.color=b.getContrast(d.color||this.color)),e&&e.color&&(f.color=e.color),d.dataLabel.addClass("highcharts-drilldown-data-label"),c||d.dataLabel.css(a).css(f))},this)});var F=function(a,b,c,e){a[c?"addClass":"removeClass"]("highcharts-drilldown-point");e||a.css({cursor:b})};f(y,"afterDrawTracker",function(){var a=this.chart.styledMode;this.points.forEach(function(b){b.drilldown&&b.graphic&&F(b.graphic,"pointer",!0,a)})});f(x,"afterSetState",
function(){var a=this.series.chart.styledMode;this.drilldown&&this.series.halo&&"hover"===this.state?F(this.series.halo,"pointer",!0,a):this.series.halo&&F(this.series.halo,"auto",!1,a)});f(h,"drillup",function(){this.resetZoomButton&&(this.resetZoomButton=this.resetZoomButton.destroy())})});t(a,"masters/modules/drilldown.src.js",[],function(){})});
//# sourceMappingURL=drilldown.js.map