/*
 Highmaps JS v9.3.2 (2021-12-20)

 Highmaps as a plugin for Highcharts or Highcharts Stock.

 (c) 2011-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(x){c(x);c.Highcharts=x;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function x(c,k,n,q){c.hasOwnProperty(k)||(c[k]=q.apply(null,n))}c=c?c._modules:{};x(c,"Core/Axis/Color/ColorAxisComposition.js",[c["Core/Color/Color.js"],c["Core/Utilities.js"]],function(c,k){var n=c.parse,
q=k.addEvent,r=k.extend,g=k.merge,f=k.pick,a=k.splat,t;(function(m){function t(){var b=this,l=this.options;this.colorAxis=[];l.colorAxis&&(l.colorAxis=a(l.colorAxis),l.colorAxis.forEach(function(l,v){l.index=v;new B(b,l)}))}function e(b){var l=this,v=function(d){d=b.allItems.indexOf(d);-1!==d&&(l.destroyItem(b.allItems[d]),b.allItems.splice(d,1))},d=[],u,e;(this.chart.colorAxis||[]).forEach(function(b){(u=b.options)&&u.showInLegend&&(u.dataClasses&&u.visible?d=d.concat(b.getDataClassLegendSymbols()):
u.visible&&d.push(b),b.series.forEach(function(b){if(!b.options.showInLegend||u.dataClasses)"point"===b.options.legendType?b.points.forEach(function(b){v(b)}):v(b)}))});for(e=d.length;e--;)b.allItems.unshift(d[e])}function b(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})}function d(){var b=this.chart.colorAxis;b&&b.forEach(function(b,l,d){b.update({},d)})}function p(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}
function w(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]}function z(b){var l=this,d=b?"show":"hide";l.visible=l.options.visible=!!b;["graphic","dataLabel"].forEach(function(b){if(l[b])l[b][d]()});this.series.buildKDTree()}function h(){var b=this,l=this.options.nullColor,d=this.colorAxis,v=this.colorKey;(this.data.length?this.data:this.points).forEach(function(u){var e=u.getNestedProperty(v);(e=u.options.color||(u.isNull||null===u.value?l:d&&
"undefined"!==typeof e?d.toColor(e,u):u.color||b.color))&&u.color!==e&&(u.color=e,"point"===b.options.legendType&&u.legendItem&&b.chart.legend.colorizeItem(u,u.visible))})}function u(b){var l=b.prototype.createAxis;b.prototype.createAxis=function(b,d){if("colorAxis"!==b)return l.apply(this,arguments);var u=new B(this,g(d.axis,{index:this[b].length,isX:!1}));this.isDirtyLegend=!0;this.axes.forEach(function(b){b.series=[]});this.series.forEach(function(b){b.bindAxes();b.isDirtyData=!0});f(d.redraw,
!0)&&this.redraw(d.animation);return u}}function A(){this.elem.attr("fill",n(this.start).tweenTo(n(this.end),this.pos),void 0,!0)}function l(){this.elem.attr("stroke",n(this.start).tweenTo(n(this.end),this.pos),void 0,!0)}var v=[],B;m.compose=function(a,f,m,g,y){B||(B=a);-1===v.indexOf(f)&&(v.push(f),a=f.prototype,a.collectionsWithUpdate.push("colorAxis"),a.collectionsWithInit.colorAxis=[a.addColorAxis],q(f,"afterGetAxes",t),u(f));-1===v.indexOf(m)&&(v.push(m),f=m.prototype,f.fillSetter=A,f.strokeSetter=
l);-1===v.indexOf(g)&&(v.push(g),q(g,"afterGetAllItems",e),q(g,"afterColorizeItem",b),q(g,"afterUpdate",d));-1===v.indexOf(y)&&(v.push(y),r(y.prototype,{optionalAxis:"colorAxis",translateColors:h}),r(y.prototype.pointClass.prototype,{setVisible:z}),q(y,"afterTranslate",p),q(y,"bindAxes",w))};m.pointSetVisible=z})(t||(t={}));return t});x(c,"Core/Axis/Color/ColorAxisDefaults.js",[],function(){return{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,
offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0}});x(c,"Core/Axis/Color/ColorAxis.js",[c["Core/Axis/Axis.js"],c["Core/Color/Color.js"],c["Core/Axis/Color/ColorAxisComposition.js"],c["Core/Axis/Color/ColorAxisDefaults.js"],c["Core/Globals.js"],c["Core/Legend/LegendSymbol.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k,n,q,r,g,f,a){var t=this&&this.__extends||
function(){var b=function(d,u){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,l){b.__proto__=l}||function(b,l){for(var d in l)l.hasOwnProperty(d)&&(b[d]=l[d])};return b(d,u)};return function(d,u){function e(){this.constructor=d}b(d,u);d.prototype=null===u?Object.create(u):(e.prototype=u.prototype,new e)}}(),m=k.parse,y=r.noop,e=f.series,b=a.extend,d=a.isNumber,p=a.merge,w=a.pick;k=function(a){function h(b,d){var l=a.call(this,b,d)||this;l.beforePadding=!1;l.chart=void 0;l.coll=
"colorAxis";l.dataClasses=void 0;l.legendItem=void 0;l.legendItems=void 0;l.name="";l.options=void 0;l.stops=void 0;l.visible=!0;l.init(b,d);return l}t(h,a);h.compose=function(b,d,l,v){n.compose(h,b,d,l,v)};h.prototype.init=function(b,d){var l=b.options.legend||{},u=d.layout?"vertical"!==d.layout:"vertical"!==l.layout,e=d.visible;l=p(h.defaultColorAxisOptions,d,{showEmpty:!1,title:null,visible:l.enabled&&!1!==e});this.coll="colorAxis";this.side=d.side||u?2:1;this.reversed=d.reversed||!u;this.opposite=
!u;a.prototype.init.call(this,b,l);this.userOptions.visible=e;d.dataClasses&&this.initDataClasses(d);this.initStops();this.horiz=u;this.zoomEnabled=!1};h.prototype.initDataClasses=function(b){var d=this.chart,l=this.options,u=b.dataClasses.length,e,a=0,h=d.options.chart.colorCount;this.dataClasses=e=[];this.legendItems=[];(b.dataClasses||[]).forEach(function(b,v){b=p(b);e.push(b);if(d.styledMode||!b.color)"category"===l.dataClassColor?(d.styledMode||(v=d.options.colors,h=v.length,b.color=v[a]),b.colorIndex=
a,a++,a===h&&(a=0)):b.color=m(l.minColor).tweenTo(m(l.maxColor),2>u?.5:v/(u-1))})};h.prototype.hasData=function(){return!!(this.tickPositions||[]).length};h.prototype.setTickPositions=function(){if(!this.dataClasses)return a.prototype.setTickPositions.call(this)};h.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=m(b[1])})};h.prototype.setOptions=function(b){a.prototype.setOptions.call(this,b);
this.options.crosshair=this.options.marker};h.prototype.setAxisSize=function(){var b=this.legendSymbol,d=this.chart,l=d.options.legend||{},e,a;b?(this.left=l=b.attr("x"),this.top=e=b.attr("y"),this.width=a=b.attr("width"),this.height=b=b.attr("height"),this.right=d.chartWidth-l-a,this.bottom=d.chartHeight-e-b,this.len=this.horiz?a:b,this.pos=this.horiz?l:e):this.len=(this.horiz?l.symbolWidth:l.symbolHeight)||h.defaultLegendLength};h.prototype.normalizedValue=function(b){this.logarithmic&&(b=this.logarithmic.log2lin(b));
return 1-(this.max-b)/(this.max-this.min||1)};h.prototype.toColor=function(b,d){var l=this.dataClasses,e=this.stops,a;if(l)for(a=l.length;a--;){var u=l[a];var p=u.from;e=u.to;if(("undefined"===typeof p||b>=p)&&("undefined"===typeof e||b<=e)){var h=u.color;d&&(d.dataClass=a,d.colorIndex=u.colorIndex);break}}else{b=this.normalizedValue(b);for(a=e.length;a--&&!(b>e[a][0]););p=e[a]||e[a+1];e=e[a+1]||p;b=1-(e[0]-b)/(e[0]-p[0]||1);h=p.color.tweenTo(e.color,b)}return h};h.prototype.getOffset=function(){var b=
this.legendGroup,d=this.chart.axisOffset[this.side];b&&(this.axisParent=b,a.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=d)};h.prototype.setLegendColor=function(){var b=this.reversed,d=b?1:0;b=b?0:1;d=this.horiz?[d,0,b,0]:[0,b,0,d];this.legendColor={linearGradient:{x1:d[0],y1:d[1],x2:d[2],y2:d[3]},stops:this.stops}};h.prototype.drawLegendSymbol=function(b,d){var l=b.padding,e=b.options,a=this.horiz,u=w(e.symbolWidth,
a?h.defaultLegendLength:12),p=w(e.symbolHeight,a?12:h.defaultLegendLength),A=w(e.labelPadding,a?16:30);e=w(e.itemDistance,10);this.setLegendColor();d.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,u,p).attr({zIndex:1}).add(d.legendGroup);this.legendItemWidth=u+l+(a?e:A);this.legendItemHeight=p+l+(a?A:0)};h.prototype.setState=function(b){this.series.forEach(function(d){d.setState(b)})};h.prototype.setVisible=function(){};h.prototype.getSeriesExtremes=function(){var b=this.series,d=b.length,
l;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var a=b[d];var p=a.colorKey=w(a.options.colorKey,a.colorKey,a.pointValKey,a.zoneAxis,"y");var h=a.pointArrayMap;var f=a[p+"Min"]&&a[p+"Max"];if(a[p+"Data"])var m=a[p+"Data"];else if(h){m=[];h=h.indexOf(p);var t=a.yData;if(0<=h&&t)for(l=0;l<t.length;l++)m.push(w(t[l][h],t[l]))}else m=a.yData;f?(a.minColorValue=a[p+"Min"],a.maxColorValue=a[p+"Max"]):(m=e.prototype.getExtremes.call(a,m),a.minColorValue=m.dataMin,a.maxColorValue=m.dataMax);"undefined"!==
typeof a.minColorValue&&(this.dataMin=Math.min(this.dataMin,a.minColorValue),this.dataMax=Math.max(this.dataMax,a.maxColorValue));f||e.prototype.applyExtremes.call(a)}};h.prototype.drawCrosshair=function(b,d){var l=d&&d.plotX,e=d&&d.plotY,p=this.pos,u=this.len;if(d){var h=this.toPixels(d.getNestedProperty(d.series.colorKey));h<p?h=p-2:h>p+u&&(h=p+u+2);d.plotX=h;d.plotY=this.len-h;a.prototype.drawCrosshair.call(this,b,d);d.plotX=l;d.plotY=e;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&
(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};h.prototype.getPlotLinePath=function(b){var e=this.left,l=b.translatedValue,p=this.top;return d(l)?this.horiz?[["M",l-4,p-6],["L",l+4,p-6],["L",l,p],["Z"]]:[["M",e,l],["L",e-6,l+6],["L",e-6,l-6],["Z"]]:a.prototype.getPlotLinePath.call(this,b)};h.prototype.update=function(b,d){var l=this.chart.legend;
this.series.forEach(function(b){b.isDirtyData=!0});(b.dataClasses&&l.allItems||this.dataClasses)&&this.destroyItems();a.prototype.update.call(this,b,d);this.legendItem&&(this.setLegendColor(),l.colorizeItem(this,!0))};h.prototype.destroyItems=function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(d){b.legend.destroyItem(d)});b.isDirtyLegend=!0};h.prototype.destroy=function(){this.chart.isDirtyLegend=!0;this.destroyItems();a.prototype.destroy.apply(this,
[].slice.call(arguments))};h.prototype.remove=function(b){this.destroyItems();a.prototype.remove.call(this,b)};h.prototype.getDataClassLegendSymbols=function(){var d=this,a=d.chart,l=d.legendItems,e=a.options.legend,p=e.valueDecimals,h=e.valueSuffix||"",f;l.length||d.dataClasses.forEach(function(e,u){var v=e.from,m=e.to,w=a.numberFormatter,t=!0;f="";"undefined"===typeof v?f="< ":"undefined"===typeof m&&(f="> ");"undefined"!==typeof v&&(f+=w(v,p)+h);"undefined"!==typeof v&&"undefined"!==typeof m&&
(f+=" - ");"undefined"!==typeof m&&(f+=w(m,p)+h);l.push(b({chart:a,name:f,options:{},drawLegendSymbol:g.drawRectangle,visible:!0,setState:y,isDataClass:!0,setVisible:function(){t=d.visible=!t;d.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===u&&b.setVisible(t)})});a.legend.colorizeItem(this,t)}},e))});return l};h.defaultColorAxisOptions=q;h.defaultLegendLength=200;h.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return h}(c);Array.prototype.push.apply(c.keepProps,
k.keepProps);"";return k});x(c,"Maps/MapNavigationOptionsDefault.js",[c["Core/DefaultOptions.js"],c["Core/Utilities.js"]],function(c,k){k=k.extend;var n={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};k(c.defaultOptions.lang,
{zoomIn:"Zoom in",zoomOut:"Zoom out"});return c.defaultOptions.mapNavigation=n});x(c,"Maps/MapNavigation.js",[c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,k,n){function q(b){b&&(b.preventDefault&&b.preventDefault(),b.stopPropagation&&b.stopPropagation(),b.cancelBubble=!0)}function r(b){this.navButtons=[];this.init(b)}var g=k.doc,f=n.addEvent,a=n.extend,t=n.isNumber,m=n.merge,y=n.objectEach,e=n.pick;r.prototype.init=function(b){this.chart=b};r.prototype.update=function(b){var d=
this,p=this.chart,w=p.options.mapNavigation,t,h,u,A,l=function(b){this.handler.call(p,b);q(b)},v=d.navButtons;b&&(w=p.options.mapNavigation=m(p.options.mapNavigation,b));for(;v.length;)v.pop().destroy();e(w.enableButtons,w.enabled)&&!p.renderer.forExport&&(d.navButtonsGroup||(d.navButtonsGroup=p.renderer.g().attr({zIndex:4}).add()),y(w.buttons,function(b,e){b=m(w.buttonOptions,b);!p.styledMode&&b.theme&&(t=b.theme,t.style=m(b.theme.style,b.style),u=(h=t.states)&&h.hover,A=h&&h.select,delete t.states);
var g=p.renderer.button(b.text||"",0,0,l,t,u,A,void 0,"zoomIn"===e?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[e]).attr({width:b.width,height:b.height,title:p.options.lang[e],padding:b.padding,zIndex:5}).add(d.navButtonsGroup);g.handler=b.onclick;f(g.element,"dblclick",q);v.push(g);a(b,{width:g.width,height:2*g.height});if(p.hasLoaded)g.align(b,!1,b.alignTo);else var y=f(p,"load",function(){g.element&&g.align(b,!1,b.alignTo);y()})}),
b=function(){var b=p.exportingGroup&&p.exportingGroup.getBBox();if(b){var a=d.navButtonsGroup.getBBox();if(!(a.x>=b.x+b.width||a.x+a.width<=b.x||a.y>=b.y+b.height||a.y+a.height<=b.y)){var l=-a.y-a.height+b.y-5;b=b.y+b.height-a.y+5;d.navButtonsGroup.attr({translateY:"bottom"===(w.buttonOptions&&w.buttonOptions.verticalAlign)?l:b})}}},p.hasLoaded||f(p,"render",b));this.updateEvents(w)};r.prototype.updateEvents=function(b){var d=this.chart;e(b.enableDoubleClickZoom,b.enabled)||b.enableDoubleClickZoomTo?
this.unbindDblClick=this.unbindDblClick||f(d.container,"dblclick",function(b){d.pointer.onContainerDblClick(b)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());e(b.enableMouseWheelZoom,b.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||f(d.container,void 0!==g.onwheel?"wheel":void 0!==g.onmousewheel?"mousewheel":"DOMMouseScroll",function(b){d.pointer.inClass(b.target,"highcharts-no-mousewheel")||(d.pointer.onContainerMouseWheel(b),q(b));return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=
this.unbindMouseWheel())};a(c.prototype,{fitToBox:function(b,d){[["x","width"],["y","height"]].forEach(function(a){var e=a[0];a=a[1];b[e]+b[a]>d[e]+d[a]&&(b[a]>d[a]?(b[a]=d[a],b[e]=d[e]):b[e]=d[e]+d[a]-b[a]);b[a]>d[a]&&(b[a]=d[a]);b[e]<d[e]&&(b[e]=d[e])});return b},mapZoom:function(b,d,a,e,f){this.mapView&&(t(b)&&(b=Math.log(b)/Math.log(.5)),this.mapView.zoomBy(b,t(d)&&t(a)?this.mapView.projection.inverse([d,a]):void 0,t(e)&&t(f)?[e,f]:void 0))}});f(c,"beforeRender",function(){this.mapNavigation=
new r(this);this.mapNavigation.update()});k.MapNavigation=r});x(c,"Maps/MapPointer.js",[c["Core/Pointer.js"],c["Core/Utilities.js"]],function(c,k){var n=k.defined,q=k.extend,r=k.pick;k=k.wrap;var g=0,f;q(c.prototype,{onContainerDblClick:function(a){var f=this.chart;a=this.normalize(a);f.options.mapNavigation.enableDoubleClickZoomTo?f.pointer.inClass(a.target,"highcharts-tracker")&&f.hoverPoint&&f.hoverPoint.zoomTo():f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(.5,void 0,void 0,
a.chartX,a.chartY)},onContainerMouseWheel:function(a){var t=this.chart;a=this.normalize(a);var m=n(a.wheelDelta)&&-a.wheelDelta/120||a.deltaY||a.detail;1<=Math.abs(m)&&(g+=Math.abs(m),f&&clearTimeout(f),f=setTimeout(function(){g=0},50));10>g&&t.isInsidePlot(a.chartX-t.plotLeft,a.chartY-t.plotTop)&&t.mapView&&t.mapView.zoomBy((t.options.mapNavigation.mouseWheelSensitivity-1)*-m,void 0,[a.chartX,a.chartY],1>Math.abs(m)?!1:void 0)}});k(c.prototype,"zoomOption",function(a){var f=this.chart.options.mapNavigation;
r(f.enableTouchZoom,f.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});k(c.prototype,"pinchTranslate",function(a,f,m,g,e,b,d){a.call(this,f,m,g,e,b,d);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=g.scaleX>g.scaleY,this.pinchTranslateDirection(!a,f,m,g,e,b,d,a?g.scaleX:g.scaleY))})});x(c,"Series/ColorMapMixin.js",[c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,k,n){var q=c.noop;c=c.seriesTypes;var r=n.defined;
n=n.addEvent;n(k,"afterSetState",function(g){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:g&&"hover"===g.state?1:0})});return{PointMixin:{dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value}},SeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:q,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:c.column.prototype.pointAttribs,
colorAttribs:function(g){var f={};!r(g.color)||g.state&&"normal"!==g.state||(f[this.colorProp||"fill"]=g.color);return f}}}});x(c,"Maps/MapViewOptionsDefault.js",[],function(){return{center:[0,0],maxZoom:void 0,padding:0,projection:void 0,zoom:void 0}});x(c,"Maps/Projections/LambertConformalConic.js",[],function(){var c=Math.sign||function(g){return 0===g?0:0<g?1:-1},k=Math.PI/180,n=Math.PI/2,q=0,r=0;return{init:function(g){var f=(g.parallels||[]).map(function(a){return a*k});g=f[0]||0;f=f[1]||g;
var a=Math.cos(g);q=g===f?Math.sin(g):Math.log(a/Math.cos(f))/Math.log(Math.tan((n+f)/2)/Math.tan((n+g)/2));1e-10>Math.abs(q)&&(q=1e-10*(c(q)||1));r=a*Math.pow(Math.tan((n+g)/2),q)/q},forward:function(g){var f=g[0]*k;g=g[1]*k;0<r?g<-n+.000001&&(g=-n+.000001):g>n-.000001&&(g=n-.000001);g=r/Math.pow(Math.tan((n+g)/2),q);return[g*Math.sin(q*f)*63.78137,63.78137*(r-g*Math.cos(q*f))]},inverse:function(g){var f=g[0]/63.78137;g=r-g[1]/63.78137;var a=c(q)*Math.sqrt(f*f+g*g),t=Math.atan2(f,Math.abs(g))*c(g);
0>g*q&&(t-=Math.PI*c(f)*c(g));return[t/q/k,(2*Math.atan(Math.pow(r/a,1/q))-n)/k]}}});x(c,"Maps/Projections/EqualEarth.js",[],function(){var c=Math.sqrt(3)/2;return{forward:function(k){var n=Math.PI/180,q=Math.asin(c*Math.sin(k[1]*n)),r=q*q,g=r*r*r;return[k[0]*n*Math.cos(q)*74.03120656864502/(c*(1.340264+3*-.081106*r+g*(7*.000893+.034164*r))),74.03120656864502*q*(1.340264+-.081106*r+g*(.000893+.003796*r))]},inverse:function(k){var n=k[0]/74.03120656864502;k=k[1]/74.03120656864502;var q=180/Math.PI,
r=k,g;for(g=0;12>g;++g){var f=r*r;var a=f*f*f;var t=r*(1.340264+-.081106*f+a*(.000893+.003796*f))-k;f=1.340264+3*-.081106*f+a*(7*.000893+.034164*f);r-=t/=f;if(1e-9>Math.abs(t))break}f=r*r;return[q*c*n*(1.340264+3*-.081106*f+f*f*f*(7*.000893+.034164*f))/Math.cos(r),q*Math.asin(Math.sin(r)/c)]}}});x(c,"Maps/Projections/Miller.js",[],function(){var c=Math.PI/4,k=Math.PI/180;return{forward:function(n){return[n[0]*k*63.78137,79.7267125*Math.log(Math.tan(c+.4*n[1]*k))]},inverse:function(n){return[n[0]/
63.78137/k,2.5*(Math.atan(Math.exp(n[1]/63.78137*.8))-c)/k]}}});x(c,"Maps/Projections/Orthographic.js",[],function(){var c=Math.PI/180;return{forward:function(k){var n=k[0];if(-90>n||90<n)return[NaN,NaN];k=k[1]*c;return[Math.cos(k)*Math.sin(n*c)*63.78460826781007,63.78460826781007*Math.sin(k)]},inverse:function(k){var n=k[0]/63.78460826781007;k=k[1]/63.78460826781007;var q=Math.sqrt(n*n+k*k),r=Math.asin(q),g=Math.sin(r);return[Math.atan2(n*g,q*Math.cos(r))/c,Math.asin(q&&k*g/q)/c]}}});x(c,"Maps/Projections/WebMercator.js",
[],function(){var c=Math.PI/180;return{forward:function(k){if(85.0511287798<Math.abs(k[1]))return[NaN,NaN];var n=Math.sin(k[1]*c);return[63.78137*k[0]*c,63.78137*Math.log((1+n)/(1-n))/2]},inverse:function(k){return[k[0]/(63.78137*c),(2*Math.atan(Math.exp(k[1]/63.78137))-Math.PI/2)/c]},maxLatitude:85.0511287798}});x(c,"Maps/Projections/ProjectionRegistry.js",[c["Maps/Projections/LambertConformalConic.js"],c["Maps/Projections/EqualEarth.js"],c["Maps/Projections/Miller.js"],c["Maps/Projections/Orthographic.js"],
c["Maps/Projections/WebMercator.js"]],function(c,k,n,q,r){return{EqualEarth:k,LambertConformalConic:c,Miller:n,Orthographic:q,WebMercator:r}});x(c,"Maps/Projection.js",[c["Maps/Projections/ProjectionRegistry.js"],c["Core/Utilities.js"]],function(c,k){var n=this&&this.__spreadArrays||function(){for(var f=0,a=0,c=arguments.length;a<c;a++)f+=arguments[a].length;f=Array(f);var m=0;for(a=0;a<c;a++)for(var g=arguments[a],e=0,b=g.length;e<b;e++,m++)f[m]=g[e];return f},q=k.erase,r=2*Math.PI/360,g=function(f){-180>
f&&(f+=360);180<f&&(f-=360);return f};return function(){function f(a){void 0===a&&(a={});this.hasGeoProjection=this.hasCoordinates=!1;this.maxLatitude=90;this.options=a;var c=a.name,m=a.rotation;this.rotator=m?this.getRotator(m):void 0;var g=this.def=c?f.registry[c]:void 0,e=this.rotator;g&&(g.init&&g.init(a),this.maxLatitude=g.maxLatitude||90,this.hasGeoProjection=!0);e&&g?(this.forward=function(b){b=e.forward(b);return g.forward(b)},this.inverse=function(b){b=g.inverse(b);return e.inverse(b)}):
g?(this.forward=g.forward,this.inverse=g.inverse):e&&(this.forward=e.forward,this.inverse=e.inverse)}f.add=function(a,c){f.registry[a]=c};f.greatCircle=function(a,f,c){var m=Math.atan2,e=Math.cos,b=Math.sin,d=Math.sqrt,p=a[1]*r,g=a[0]*r,t=f[1]*r,h=f[0]*r,u=t-p,A=h-g;u=b(u/2)*b(u/2)+e(p)*e(t)*b(A/2)*b(A/2);u=2*m(d(u),d(1-u));var l=Math.round(6371E3*u/5E5);A=[];c&&A.push(a);if(1<l)for(l=a=1/l;.999>l;l+=a){var v=b((1-l)*u)/b(u),k=b(l*u)/b(u),n=v*e(p)*e(g)+k*e(t)*e(h),q=v*e(p)*b(g)+k*e(t)*b(h);v=v*b(p)+
k*b(t);v=m(v,d(n*n+q*q));n=m(q,n);A.push([n/r,v/r])}c&&A.push(f);return A};f.insertGreatCircles=function(a){for(var c=a.length-1;c--;)if(10<Math.max(Math.abs(a[c][0]-a[c+1][0]),Math.abs(a[c][1]-a[c+1][1]))){var m=f.greatCircle(a[c],a[c+1]);m.length&&a.splice.apply(a,n([c+1,0],m))}};f.toString=function(a){a=a||{};var f=a.rotation;return[a.name,f&&f.join(",")].join(";")};f.prototype.getRotator=function(a){var f=a[0]*r,c=(a[1]||0)*r;a=(a[2]||0)*r;var g=Math.cos(c),e=Math.sin(c),b=Math.cos(a),d=Math.sin(a);
if(0!==f||0!==c||0!==a)return{forward:function(a){var p=a[0]*r+f,c=a[1]*r,h=Math.cos(c);a=Math.cos(p)*h;p=Math.sin(p)*h;c=Math.sin(c);h=c*g+a*e;return[Math.atan2(p*b-h*d,a*g-c*e)/r,Math.asin(h*b+p*d)/r]},inverse:function(a){var p=a[0]*r,c=a[1]*r,h=Math.cos(c);a=Math.cos(p)*h;p=Math.sin(p)*h;c=Math.sin(c);h=c*b-p*d;return[(Math.atan2(p*b+c*d,a*g+h*e)-f)/r,Math.asin(h*g-a*e)/r]}}};f.prototype.forward=function(a){return a};f.prototype.inverse=function(a){return a};f.prototype.clipOnAntimeridian=function(a,
c){var m=[],t=[a];a.forEach(function(b,d){var e=a[d-1];if(!d){if(!c)return;e=a[a.length-1]}var l=e[0],h=b[0];(-90>l||90<l)&&(-90>h||90<h)&&0<l!==0<h&&m.push({i:d,lat:e[1]+(180-e[0])/(b[0]-e[0])*(b[1]-e[1]),direction:0>l?1:-1,previousLonLat:e,lonLat:b})});if(m.length)if(c){if(1===m.length%2){var e=m.slice().sort(function(b,d){return Math.abs(d.lat)-Math.abs(b.lat)})[0];q(m,e)}for(var b=m.length-2;0<=b;){var d=m[b].i,p=g(180+.000001*m[b].direction),w=g(180-.000001*m[b].direction);d=a.splice.apply(a,
n([d,m[b+1].i-d],f.greatCircle([p,m[b].lat],[p,m[b+1].lat],!0)));d.push.apply(d,f.greatCircle([w,m[b+1].lat],[w,m[b].lat],!0));t.push(d);b-=2}if(e)for(d=0;d<t.length;d++)if(b=t[d],w=b.indexOf(e.lonLat),-1<w){d=(0>e.lat?-1:1)*this.maxLatitude;p=g(180+.000001*e.direction);var k=g(180-.000001*e.direction);e=f.greatCircle([p,e.lat],[p,d],!0).concat(f.greatCircle([k,d],[k,e.lat],!0));b.splice.apply(b,n([w,0],e));break}}else for(b=m.length;b--;)d=m[b].i,d=a.splice(d,a.length,[g(180+.000001*m[b].direction),
m[b].lat]),d.unshift([g(180-.000001*m[b].direction),m[b].lat]),t.push(d);return t};f.prototype.path=function(a){var c=this,g=this.def,k=this.rotator,e=[],b="Polygon"===a.type||"MultiPolygon"===a.type,d=this.hasGeoProjection,p="Orthographic"!==this.options.name,w=p?k:void 0,n=p?g||this:this,h=function(a){a=a.map(function(b){if(p){w&&(b=w.forward(b));var d=b[0];.000001>Math.abs(d-180)&&(d=180>d?179.999999:180.000001);b=[d,b[1]]}return b});var h=[a];d&&(f.insertGreatCircles(a),p&&(h=c.clipOnAntimeridian(a,
b)));h.forEach(function(a){if(!(2>a.length))for(var l=!1,h,p,u=!1,g=function(b){l?e.push(["L",b[0],b[1]]):(e.push(["M",b[0],b[1]]),l=!0)},m=0;m<a.length;m++){var w=a[m],t=n.forward(w);isNaN(t[0])||isNaN(t[1])||d&&!(w[1]<=c.maxLatitude&&w[1]>=-c.maxLatitude)?u=!0:(b&&!h&&(h=w,a.push(w)),u&&p&&(b&&d?f.greatCircle(p,w).forEach(function(b){return g(n.forward(b))}):l=!1),g(t),p=w,u=!1)}})};"LineString"===a.type?h(a.coordinates):"MultiLineString"===a.type?a.coordinates.forEach(function(b){return h(b)}):
"Polygon"===a.type?(a.coordinates.forEach(function(b){return h(b)}),e.length&&e.push(["Z"])):"MultiPolygon"===a.type&&(a.coordinates.forEach(function(b){b.forEach(function(b){return h(b)})}),e.length&&e.push(["Z"]));return e};f.registry=c;return f}()});x(c,"Maps/MapView.js",[c["Maps/MapViewOptionsDefault.js"],c["Maps/Projection.js"],c["Core/Utilities.js"]],function(c,k,n){var q=n.addEvent,r=n.clamp,g=n.fireEvent,f=n.isNumber,a=n.merge,t=n.pick,m=n.relativeLength;return function(){function n(e,b){var d=
this;this.userOptions=b||{};b=a(c,b);this.chart=e;this.center=b.center;this.options=b;this.projection=new k(b.projection);this.zoom=b.zoom||0;q(e,"afterSetChartSize",function(){if(void 0===d.minZoom||d.minZoom===d.zoom)d.fitToBounds(void 0,void 0,!1),f(d.userOptions.zoom)&&(d.zoom=d.userOptions.zoom),d.userOptions.center&&a(!0,d.center,d.userOptions.center)});var p,g,m;b=function(b){var a=e.pointer.pinchDown,h=e.mouseDownX,l=e.mouseDownY;1===a.length&&(h=a[0].chartX,l=a[0].chartY);if("number"===typeof h&&
"number"===typeof l){var c=h+","+l,f=b.originalEvent;a=f.chartX;f=f.chartY;c!==g&&(g=c,p=d.projection.forward(d.center),m=(d.projection.options.rotation||[0,0]).slice());"Orthographic"===d.projection.options.name&&3>(d.minZoom||Infinity)?(c=440/(d.getScale()*Math.min(e.plotWidth,e.plotHeight)),m&&(h=(h-a)*c-m[0],l=r(-m[1]-(l-f)*c,-80,80),d.update({projection:{rotation:[-h,-l]},center:[h,l],zoom:d.zoom},!0,!1))):(c=d.getScale(),l=d.projection.inverse([p[0]+(h-a)/c,p[1]-(l-f)/c]),d.setView(l,void 0,
!0,!1));b.preventDefault()}};q(e,"pan",b);q(e,"touchpan",b);q(e,"selection",function(b){if(b.resetSelection)d.zoomBy();else{var a=b.x-e.plotLeft,c=b.y-e.plotTop,l=d.pixelsToProjectedUnits({x:a,y:c}),h=l.y;l=l.x;a=d.pixelsToProjectedUnits({x:a+b.width,y:c+b.height});d.fitToBounds({x1:l,y1:h,x2:a.x,y2:a.y},void 0,!0,b.originalEvent.touches?!1:void 0);/^touch/.test(b.originalEvent.type)||e.showResetZoom();b.preventDefault()}})}n.prototype.fitToBounds=function(a,b,d,c){void 0===d&&(d=!0);var e=a||this.getProjectedBounds();
if(e){var p=this.chart,h=p.plotWidth;p=p.plotHeight;var f=t(b,a?0:this.options.padding);b=m(f,h);f=m(f,p);h=Math.log(400.979322/Math.max((e.x2-e.x1)/((h-b)/256),(e.y2-e.y1)/((p-f)/256)))/Math.log(2);a||(this.minZoom=h);a=this.projection.inverse([(e.x2+e.x1)/2,(e.y2+e.y1)/2]);this.setView(a,h,d,c)}};n.prototype.getProjectedBounds=function(){var a=this.chart.series.reduce(function(b,a){(a=a.getProjectedBounds&&a.getProjectedBounds())&&b.push(a);return b},[]);return n.compositeBounds(a)};n.prototype.getScale=
function(){return 256/400.979322*Math.pow(2,this.zoom)};n.prototype.redraw=function(a){this.chart.series.forEach(function(b){b.useMapGeometry&&(b.isDirty=!0)});this.chart.redraw(a)};n.prototype.setView=function(a,b,d,c){void 0===d&&(d=!0);var e=!1;a&&(this.center=a);"number"===typeof b&&("number"===typeof this.minZoom&&(b=Math.max(b,this.minZoom)),"number"===typeof this.options.maxZoom&&(b=Math.min(b,this.options.maxZoom)),e=b>this.zoom,this.zoom=b);var p=this.getProjectedBounds();if(p&&!e){e=this.projection.forward(this.center);
b=this.chart;a=b.plotWidth;b=b.plotHeight;var h=this.getScale(),f=this.projectedUnitsToPixels({x:p.x1,y:p.y1}),m=this.projectedUnitsToPixels({x:p.x2,y:p.y2});p=[(p.x1+p.x2)/2,(p.y1+p.y2)/2];var l=f.x,v=m.y;m=m.x;f=f.y;m-l<a?e[0]=p[0]:0>l&&m<a?e[0]+=Math.max(l,m-a)/h:m>a&&0<l&&(e[0]+=Math.min(m-a,l)/h);f-v<b?e[1]=p[1]:0>v&&f<b?e[1]-=Math.max(v,f-b)/h:f>b&&0<v&&(e[1]-=Math.min(f-b,v)/h);this.center=this.projection.inverse(e)}g(this,"afterSetView");d&&this.redraw(c)};n.prototype.projectedUnitsToPixels=
function(a){var b=this.getScale(),d=this.projection.forward(this.center);return{x:this.chart.plotWidth/2-b*(d[0]-a.x),y:this.chart.plotHeight/2+b*(d[1]-a.y)}};n.prototype.pixelsToProjectedUnits=function(a){var b=a.x;a=a.y;var d=this.getScale(),e=this.projection.forward(this.center);return{x:e[0]+(b-this.chart.plotWidth/2)/d,y:e[1]-(a-this.chart.plotHeight/2)/d}};n.prototype.update=function(e,b,d){void 0===b&&(b=!0);var c=e.projection;c=c&&k.toString(c)!==k.toString(this.options.projection);a(!0,this.userOptions,
e);a(!0,this.options,e);c&&(this.chart.series.forEach(function(b){b.clearBounds&&b.clearBounds();b.isDirty=!0;b.isDirtyData=!0}),this.projection=new k(this.options.projection),e.center||f(e.zoom)||this.fitToBounds(void 0,void 0,!1));(e.center||f(e.zoom))&&this.setView(this.options.center,e.zoom,!1);b&&this.chart.redraw(d)};n.prototype.zoomBy=function(a,b,d,c){var e=this.chart,f=this.projection.forward(this.center);b=b?this.projection.forward(b):[];var h=b[0],p=b[1];"number"===typeof a?(a=this.zoom+
a,b=void 0,d&&(h=d[0],p=d[1],d=this.getScale(),h=h-e.plotLeft-e.plotWidth/2,e=p-e.plotTop-e.plotHeight/2,h=f[0]+h/d,p=f[1]+e/d),"number"===typeof h&&"number"===typeof p&&(d=1-Math.pow(2,this.zoom)/Math.pow(2,a),h=f[0]-h,e=f[1]-p,f[0]-=h*d,f[1]+=e*d,b=this.projection.inverse(f)),this.setView(b,a,void 0,c)):this.fitToBounds(void 0,void 0,void 0,c)};n.compositeBounds=function(e){if(e.length)return e.slice(1).reduce(function(b,a){b.x1=Math.min(b.x1,a.x1);b.y1=Math.min(b.y1,a.y1);b.x2=Math.max(b.x2,a.x2);
b.y2=Math.max(b.y2,a.y2);return b},a(e[0]))};return n}()});x(c,"Maps/MapSymbols.js",[c["Core/Renderer/SVG/SVGRenderer.js"]],function(c){function k(c,k,r,g,f,a,t,m){return[["M",c+f,k],["L",c+r-a,k],["C",c+r-a/2,k,c+r,k+a/2,c+r,k+a],["L",c+r,k+g-t],["C",c+r,k+g-t/2,c+r-t/2,k+g,c+r-t,k+g],["L",c+m,k+g],["C",c+m/2,k+g,c,k+g-m/2,c,k+g-m],["L",c,k+f],["C",c,k+f/2,c+f/2,k,c+f,k],["Z"]]}c=c.prototype.symbols;c.bottombutton=function(c,q,r,g,f){f=f&&f.r||0;return k(c-1,q-1,r,g,0,0,f,f)};c.topbutton=function(c,
q,r,g,f){f=f&&f.r||0;return k(c-1,q-1,r,g,f,f,0,0)};return c});x(c,"Core/Chart/MapChart.js",[c["Core/Chart/Chart.js"],c["Core/DefaultOptions.js"],c["Maps/MapView.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,k,n,q,r){var g=this&&this.__extends||function(){var a=function(e,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return a(e,b)};return function(e,b){function d(){this.constructor=
e}a(e,b);e.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}(),f=k.getOptions,a=r.addEvent,t=r.merge,m=r.pick;c=function(c){function e(){return null!==c&&c.apply(this,arguments)||this}g(e,c);e.prototype.init=function(b,d){a(this,"afterInit",function(){this.mapView=new n(this,this.options.mapView)});var e=f().credits;b=t({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:m(e.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:m(e.mapTextFull,
"{geojson.copyright}")},mapView:{},tooltip:{followTouchMove:!1}},b);c.prototype.init.call(this,b,d)};return e}(c);(function(a){a.maps={};a.mapChart=function(e,b,d){return new a(e,b,d)};a.splitPath=function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(b){return/[A-za-z]/.test(b)?b:parseFloat(b)}));return q.prototype.pathToSegments(a)}})(c||(c={}));return c});x(c,"Series/Map/MapPoint.js",[c["Series/ColorMapMixin.js"],
c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k,n){var q=this&&this.__extends||function(){var c=function(f,a){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var f in c)c.hasOwnProperty(f)&&(a[f]=c[f])};return c(f,a)};return function(f,a){function g(){this.constructor=f}c(f,a);f.prototype=null===a?Object.create(a):(g.prototype=a.prototype,new g)}}(),r=n.extend;k=function(c){function f(){var a=null!==c&&c.apply(this,arguments)||
this;a.options=void 0;a.path=void 0;a.series=void 0;return a}q(f,c);f.getProjectedPath=function(a,c){a.projectedPath||(c&&a.geometry?(c.hasCoordinates=!0,a.projectedPath=c.path(a.geometry)):a.projectedPath=a.path);return a.projectedPath||[]};f.prototype.applyOptions=function(a,f){var m=this.series;a=c.prototype.applyOptions.call(this,a,f);f=m.joinBy;m.mapData&&m.mapMap&&(f=c.prototype.getNestedProperty.call(a,f[1]),(m="undefined"!==typeof f&&m.mapMap[f])?r(a,m):a.value=a.value||null);return a};f.prototype.onMouseOver=
function(a){n.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)c.prototype.onMouseOver.call(this,a);else this.series.onMouseOut(a)};f.prototype.zoomTo=function(){var a=this.series.chart;a.mapView&&this.bounds&&(a.mapView.fitToBounds(this.bounds,void 0,!1),this.series.isDirty=!0,a.redraw())};return f}(k.seriesTypes.scatter.prototype.pointClass);r(k.prototype,{dataLabelOnNull:c.PointMixin.dataLabelOnNull,isValid:c.PointMixin.isValid,moveToTopOnHover:c.PointMixin.moveToTopOnHover});
return k});x(c,"Series/Map/MapSeries.js",[c["Core/Animation/AnimationUtilities.js"],c["Series/ColorMapMixin.js"],c["Series/CenteredUtilities.js"],c["Core/Globals.js"],c["Core/Legend/LegendSymbol.js"],c["Core/Chart/MapChart.js"],c["Series/Map/MapPoint.js"],c["Maps/MapView.js"],c["Core/Series/Series.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,k,n,q,r,g,f,a,t,m,y,e){var b=this&&this.__extends||function(){var b=function(a,d){b=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return b(a,d)};return function(a,d){function e(){this.constructor=a}b(a,d);a.prototype=null===d?Object.create(d):(e.prototype=d.prototype,new e)}}(),d=c.animObject;c=q.noop;var p=g.maps,w=g.splitPath;g=m.seriesTypes;var z=g.column,h=g.scatter;g=e.extend;var u=e.fireEvent,A=e.getNestedProperty,l=e.isArray,v=e.isNumber,B=e.merge,E=e.objectEach,D=e.pick,F=e.splat;e=function(e){function c(){var b=
null!==e&&e.apply(this,arguments)||this;b.chart=void 0;b.data=void 0;b.group=void 0;b.joinBy=void 0;b.options=void 0;b.points=void 0;b.processedData=[];b.transformGroup=void 0;return b}b(c,e);c.prototype.animate=function(b){var a=this.chart,c=this.group,e=d(this.options.animation);a.renderer.isSVG&&(b?c.attr({translateX:a.plotLeft+a.plotWidth/2,translateY:a.plotTop+a.plotHeight/2,scaleX:.001,scaleY:.001}):c.animate({translateX:a.plotLeft,translateY:a.plotTop,scaleX:1,scaleY:1},e))};c.prototype.animateDrilldown=
function(b){var a=this.chart,d=this.group;a.renderer.isSVG&&(b?d.attr({translateX:a.plotLeft+a.plotWidth/2,translateY:a.plotTop+a.plotHeight/2,scaleX:.1,scaleY:.1,opacity:.01}):(d.animate({translateX:a.plotLeft,translateY:a.plotTop,scaleX:1,scaleY:1,opacity:1},this.chart.options.drilldown.animation),a.drilldown&&a.drilldown.fadeInGroup(this.dataLabelsGroup)))};c.prototype.animateDrillupFrom=function(){var b=this.chart;b.renderer.isSVG&&this.group.animate({translateX:b.plotLeft+b.plotWidth/2,translateY:b.plotTop+
b.plotHeight/2,scaleX:.1,scaleY:.1,opacity:.01})};c.prototype.animateDrillupTo=function(b){z.prototype.animateDrillupTo.call(this,b)};c.prototype.clearBounds=function(){this.points.forEach(function(b){delete b.bounds;delete b.projectedPath});delete this.bounds};c.prototype.doFullTranslate=function(){return!(!(this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML)&&this.hasRendered)};c.prototype.drawMapDataLabels=function(){t.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};
c.prototype.drawPoints=function(){var b=this,a=this.chart,d=this.group,c=this.svgTransform,e=a.mapView,l=a.renderer;this.transformGroup||(this.transformGroup=l.g().add(d),this.transformGroup.survive=!0);this.doFullTranslate()&&(a.hasRendered&&!a.styledMode&&this.points.forEach(function(a){a.shapeArgs&&(a.shapeArgs.fill=b.pointAttribs(a,a.state).fill)}),this.group=this.transformGroup,z.prototype.drawPoints.apply(this),this.group=d,this.points.forEach(function(d){if(d.graphic){var c="";d.name&&(c+=
"highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&(c+=" highcharts-key-"+d.properties["hc-key"].toLowerCase());c&&d.graphic.addClass(c);a.styledMode&&d.graphic.css(b.pointAttribs(d,d.selected&&"select"||void 0))}}));if(e&&c){var f=D(this.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],1),h=c.scaleX,p=0<c.scaleY?1:-1,m=this.transformGroup;if(l.globalAnimation&&a.hasRendered){var g=Number(m.attr("translateX")),v=
Number(m.attr("translateY")),u=Number(m.attr("scaleX"));m.attr({animator:0}).animate({animator:1},{step:function(b,a){b=u+(h-u)*a.pos;m.attr({translateX:g+(c.translateX-g)*a.pos,translateY:v+(c.translateY-v)*a.pos,scaleX:b,scaleY:b*p});d.element.setAttribute("stroke-width",f/b)}})}else m.attr(c),d.element.setAttribute("stroke-width",f/h)}this.drawMapDataLabels()};c.prototype.getProjectedBounds=function(){if(!this.bounds){var b=Number.MAX_VALUE,d=this.chart.mapView&&this.chart.mapView.projection,c=
[];(this.points||[]).forEach(function(a){if(a.path||a.geometry){"string"===typeof a.path?a.path=w(a.path):l(a.path)&&"M"===a.path[0]&&(a.path=y.prototype.pathToSegments(a.path));if(!a.bounds){var e=f.getProjectedPath(a,d),h=a.properties,p=-b,m=b,g=-b,u=b,k;e.forEach(function(b){var a=b[b.length-2];b=b[b.length-1];"number"===typeof a&&"number"===typeof b&&(m=Math.min(m,a),p=Math.max(p,a),u=Math.min(u,b),g=Math.max(g,b),k=!0)});k&&(e=h&&h["hc-middle-x"],e=m+(p-m)*D(a.middleX,v(e)?e:.5),h=h&&h["hc-middle-y"],
h=D(a.middleY,v(h)?h:.5),a.geometry||(h=1-h),a.bounds={midX:e,midY:g-(g-u)*h,x1:m,y1:u,x2:p,y2:g},a.labelrank=D(a.labelrank,(p-m)*(g-u)))}a.bounds&&c.push(a.bounds)}});this.bounds=a.compositeBounds(c)}return this.bounds};c.prototype.hasData=function(){return!!this.processedXData.length};c.prototype.pointAttribs=function(b,a){var d=b.series.chart,c=d.mapView;a=d.styledMode?this.colorAttribs(b):z.prototype.pointAttribs.call(this,b,a);(b=b.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||
"borderWidth"])&&c&&(b/=c.getScale());a.dashstyle&&c&&this.options.borderWidth&&(b=this.options.borderWidth/c.getScale());a["stroke-width"]=D(b,"inherit");return a};c.prototype.setData=function(){e.prototype.setData.apply(this,arguments);this.processData();this.generatePoints()};c.prototype.processData=function(){var b=this.options,a=b.data,d=this.chart.options.chart,c=d&&d.map,e=this.joinBy,h=b.keys||this.pointArrayMap,m=[],g={},u=b.mapData,k=this.chart.mapTransforms,t=this.processedData=[];!u&&
c&&(u="string"===typeof c?p[c]:c);a&&a.forEach(function(d,c){var p=0;if(v(d))t[c]={value:d};else if(l(d)){t[c]={};!b.keys&&d.length>h.length&&"string"===typeof d[0]&&(t[c]["hc-key"]=d[0],++p);for(var m=0;m<h.length;++m,++p)h[m]&&"undefined"!==typeof d[p]&&(0<h[m].indexOf(".")?f.prototype.setNestedProperty(t[c],d[p],h[m]):t[c][h[m]]=d[p])}else t[c]=a[c];e&&"_i"===e[0]&&(t[c]._i=c)});(this.chart.mapTransforms=k=d.mapTransforms||u&&u["hc-transform"]||k)&&E(k,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),
b.sinAngle=Math.sin(b.rotation))});if(u){if("FeatureCollection"===u.type||"Topology"===u.type)this.mapTitle=u.title,u=q.geojson(u,this.type,this);this.mapData=u;this.mapMap={};for(k=0;k<u.length;k++)d=u[k],c=d.properties,d._i=k,e[0]&&c&&c[e[0]]&&(d[e[0]]=c[e[0]]),g[d[e[0]]]=d;this.mapMap=g;if(e[1]){var n=e[1];t.forEach(function(b){b=A(n,b);g[b]&&m.push(g[b])})}if(b.allAreas){if(e[1]){var r=e[1];t.forEach(function(b){m.push(A(r,b))})}var w="|"+m.map(function(b){return b&&b[e[0]]}).join("|")+"|";u.forEach(function(b){e[0]&&
-1!==w.indexOf("|"+b[e[0]]+"|")||t.push(B(b,{value:null}))})}}this.processedXData=Array(t.length)};c.prototype.setOptions=function(b){b=t.prototype.setOptions.call(this,b);var a=b.joinBy;null===a&&(a="_i");a=this.joinBy=F(a);a[1]||(a[1]=a[0]);return b};c.prototype.translate=function(){var b=this.doFullTranslate(),a=this.chart.mapView,d=a&&a.projection;!this.chart.hasRendered||!this.isDirtyData&&this.hasRendered||(this.processData(),this.generatePoints(),delete this.bounds,this.getProjectedBounds());
var c;if(a){var e=a.getScale(),l=a.projection.forward(a.center);a=a.projection.hasCoordinates?-1:1;this.svgTransform=c={scaleX:e,scaleY:e*a,translateX:this.chart.plotWidth/2-l[0]*e,translateY:this.chart.plotHeight/2-l[1]*e*a}}this.points.forEach(function(a){c&&a.bounds&&v(a.bounds.midX)&&v(a.bounds.midY)&&(a.plotX=a.bounds.midX*c.scaleX+c.translateX,a.plotY=a.bounds.midY*c.scaleY+c.translateY);b&&(a.shapeType="path",a.shapeArgs={d:f.getProjectedPath(a,d)})});u(this,"afterTranslate")};c.defaultOptions=
B(h.defaultOptions,{animation:!1,dataLabels:{crop:!1,formatter:function(){var b=this.series.chart.numberFormatter,a=this.point.value;return v(a)?b(a,-1):""},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},
inactive:{opacity:1}}});return c}(h);g(e.prototype,{type:"map",axisTypes:k.SeriesMixin.axisTypes,colorAttribs:k.SeriesMixin.colorAttribs,colorKey:k.SeriesMixin.colorKey,directTouch:!0,drawDataLabels:c,drawGraph:c,drawLegendSymbol:r.drawRectangle,forceDL:!0,getCenter:n.getCenter,getExtremesFromAll:!0,getSymbol:k.SeriesMixin.getSymbol,isCartesian:!1,parallelArrays:k.SeriesMixin.parallelArrays,pointArrayMap:k.SeriesMixin.pointArrayMap,pointClass:f,preserveAspectRatio:!0,searchPoint:c,trackerGroups:k.SeriesMixin.trackerGroups,
useMapGeometry:!0});m.registerSeriesType("map",e);"";return e});x(c,"Series/MapLine/MapLineSeries.js",[c["Series/Map/MapSeries.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k,n){var q=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(c,f)};return function(c,f){function m(){this.constructor=c}a(c,f);c.prototype=
null===f?Object.create(f):(m.prototype=f.prototype,new m)}}(),r=k.series,g=n.extend,f=n.merge;n=function(a){function g(){var c=null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}q(g,a);g.prototype.pointAttribs=function(a,f){a=c.prototype.pointAttribs.call(this,a,f);a.fill=this.options.fillColor;return a};g.defaultOptions=f(c.defaultOptions,{lineWidth:1,fillColor:"none"});return g}(c);g(n.prototype,{type:"mapline",colorProp:"stroke",drawLegendSymbol:r.prototype.drawLegendSymbol,
pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"}});k.registerSeriesType("mapline",n);"";return n});x(c,"Series/MapPoint/MapPointPoint.js",[c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k){var n=this&&this.__extends||function(){var c=function(f,a){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var f in c)c.hasOwnProperty(f)&&(a[f]=c[f])};return c(f,a)};return function(f,a){function g(){this.constructor=
f}c(f,a);f.prototype=null===a?Object.create(a):(g.prototype=a.prototype,new g)}}(),q=k.isNumber,r=k.merge;return function(c){function f(){var a=null!==c&&c.apply(this,arguments)||this;a.options=void 0;a.series=void 0;return a}n(f,c);f.prototype.applyOptions=function(a,f){a="undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?r(a,this.series.chart.fromLatLonToPoint(a)):a;return c.prototype.applyOptions.call(this,a,f)};f.prototype.isValid=function(){return!!(this.options.geometry||q(this.x)&&q(this.y))};
return f}(c.seriesTypes.scatter.prototype.pointClass)});x(c,"Series/MapPoint/MapPointSeries.js",[c["Core/Globals.js"],c["Series/MapPoint/MapPointPoint.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k,n,q){var r=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,b)};return function(c,b){function d(){this.constructor=
c}a(c,b);c.prototype=null===b?Object.create(b):(d.prototype=b.prototype,new d)}}();c=c.noop;var g=n.seriesTypes.scatter,f=q.extend,a=q.fireEvent,t=q.isNumber,m=q.merge;q=function(c){function e(){var b=null!==c&&c.apply(this,arguments)||this;b.data=void 0;b.options=void 0;b.points=void 0;return b}r(e,c);e.prototype.drawDataLabels=function(){c.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)};e.prototype.translate=function(){var b=this,c=this.chart.mapView;
this.processedXData||this.processData();this.generatePoints();if(c){var e=c.projection,f=e.forward,g=e.hasCoordinates;this.points.forEach(function(a){var d=a.x;d=void 0===d?void 0:d;var e=a.y;e=void 0===e?void 0:e;var l=a.options.geometry;(l=l&&"Point"===l.type&&l.coordinates)?(e=f(l),d=e[0],e=e[1]):a.bounds&&(d=a.bounds.midX,e=a.bounds.midY);t(d)&&t(e)?(d=c.projectedUnitsToPixels({x:d,y:e}),a.plotX=d.x,a.plotY=g?d.y:b.chart.plotHeight-d.y):(a.plotX=void 0,a.plotY=void 0);a.isInside=b.isPointInside(a);
a.zone=b.zones.length?a.getZone():void 0})}a(this,"afterTranslate")};e.defaultOptions=m(g.defaultOptions,{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}});return e}(g);f(q.prototype,{type:"mappoint",axisTypes:["colorAxis"],forceDL:!0,isCartesian:!1,pointClass:k,searchPoint:c,useMapGeometry:!0});n.registerSeriesType("mappoint",q);"";return q});x(c,"Series/Bubble/BubbleLegendDefaults.js",[],function(){return{borderColor:void 0,
borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:"10px",color:"#000000"},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}});x(c,"Series/Bubble/BubbleLegendItem.js",[c["Core/Color/Color.js"],
c["Core/FormatUtilities.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,k,n,q){var r=c.parse,g=n.noop,f=q.arrayMax,a=q.arrayMin,t=q.isNumber,m=q.merge,y=q.pick,e=q.stableSort;"";return function(){function b(b,a){this.options=this.symbols=this.visible=this.selected=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=g;this.init(b,a)}b.prototype.init=
function(b,a){this.options=b;this.visible=!0;this.chart=a.chart;this.legend=a};b.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,0,this)};b.prototype.drawLegendSymbol=function(b){var a=this.chart,c=this.options,d=y(b.options.itemDistance,20),f=c.ranges,g=c.connectorDistance;this.fontMetrics=a.renderer.fontMetrics(c.labels.style.fontSize);f&&f.length&&t(f[0].value)?(e(f,function(b,a){return a.value-b.value}),this.ranges=f,this.setOptions(),this.render(),b=this.getMaxLabelSize(),
f=this.ranges[0].radius,a=2*f,g=g-f+b.width,g=0<g?g:0,this.maxLabel=b,this.movementX="left"===c.labels.align?g:0,this.legendItemWidth=a+g+d,this.legendItemHeight=a+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};b.prototype.setOptions=function(){var b=this.ranges,a=this.options,c=this.chart.series[a.seriesIndex],e=this.legend.baseline,f={zIndex:a.zIndex,"stroke-width":a.borderWidth},g={zIndex:a.zIndex,"stroke-width":a.connectorWidth},k={align:this.legend.options.rtl||"left"===a.labels.align?
"right":"left",zIndex:a.zIndex},l=c.options.marker.fillOpacity,v=this.chart.styledMode;b.forEach(function(d,h){v||(f.stroke=y(d.borderColor,a.borderColor,c.color),f.fill=y(d.color,a.color,1!==l?r(c.color).setOpacity(l).get("rgba"):c.color),g.stroke=y(d.connectorColor,a.connectorColor,c.color));b[h].radius=this.getRangeRadius(d.value);b[h]=m(b[h],{center:b[0].radius-b[h].radius+e});v||m(!0,b[h],{bubbleAttribs:m(f),connectorAttribs:m(g),labelAttribs:k})},this)};b.prototype.getRangeRadius=function(b){var a=
this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,a.ranges[a.ranges.length-1].value,a.ranges[0].value,a.minSize,a.maxSize,b)};b.prototype.render=function(){var b=this.chart.renderer,a=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=a&&this.renderRange(b)},
this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};b.prototype.renderRange=function(b){var a=this.options,c=a.labels,d=this.chart,e=d.series[a.seriesIndex],f=d.renderer,g=this.symbols;d=g.labels;var l=b.center,m=Math.abs(b.radius),k=a.connectorDistance||0,n=c.align,t=a.connectorWidth,r=this.ranges[0].radius||0,q=l-m-a.borderWidth/2+t/2,y=this.fontMetrics;y=y.f/2-(y.h-y.f)/2;var C=f.styledMode;k=this.legend.options.rtl||"left"===n?-k:k;
"center"===n&&(k=0,a.connectorDistance=0,b.labelAttribs.align="center");n=q+a.labels.y;var x=r+k+a.labels.x;g.bubbleItems.push(f.circle(r,l+((q%1?1:.5)-(t%2?0:.5)),m).attr(C?{}:b.bubbleAttribs).addClass((C?"highcharts-color-"+e.colorIndex+" ":"")+"highcharts-bubble-legend-symbol "+(a.className||"")).add(this.legendSymbol));g.connectors.push(f.path(f.crispLine([["M",r,q],["L",r+k,q]],a.connectorWidth)).attr(C?{}:b.connectorAttribs).addClass((C?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+
(a.connectorClassName||"")).add(this.legendSymbol));b=f.text(this.formatLabel(b),x,n+y).attr(C?{}:b.labelAttribs).css(C?{}:c.style).addClass("highcharts-bubble-legend-labels "+(a.labels.className||"")).add(this.legendSymbol);d.push(b);b.placed=!0;b.alignAttr={x:x,y:n+y}};b.prototype.getMaxLabelSize=function(){var b,a;this.symbols.labels.forEach(function(c){a=c.getBBox(!0);b=b?a.width>b.width?a:b:a});return b||{}};b.prototype.formatLabel=function(b){var a=this.options,c=a.labels.formatter;a=a.labels.format;
var d=this.chart.numberFormatter;return a?k.format(a,b):c?c.call(b):d(b.value,1)};b.prototype.hideOverlappingLabels=function(){var b=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(b.hideOverlappingLabels(a.labels),a.labels.forEach(function(b,c){b.newOpacity?b.newOpacity!==b.oldOpacity&&a.connectors[c].show():a.connectors[c].hide()}))};b.prototype.getRanges=function(){var b=this.legend.bubbleLegend,c=b.options.ranges,e,g=Number.MAX_VALUE,h=-Number.MAX_VALUE;b.chart.series.forEach(function(b){b.isBubble&&
!b.ignoreSeries&&(e=b.zData.filter(t),e.length&&(g=y(b.options.zMin,Math.min(g,Math.max(a(e),!1===b.options.displayNegative?b.options.zThreshold:-Number.MAX_VALUE))),h=y(b.options.zMax,Math.max(h,f(e)))))});var k=g===h?[{value:h}]:[{value:g},{value:(g+h)/2},{value:h,autoRanges:!0}];c.length&&c[0].radius&&k.reverse();k.forEach(function(b,a){c&&c[a]&&(k[a]=m(c[a],b))});return k};b.prototype.predictBubbleSizes=function(){var b=this.chart,a=this.fontMetrics,c=b.legend.options,e=c.floating,f=(c="horizontal"===
c.layout)?b.legend.lastLineHeight:0,g=b.plotSizeX,m=b.plotSizeY,l=b.series[this.options.seriesIndex],v=l.getPxExtremes();b=Math.ceil(v.minPxSize);v=Math.ceil(v.maxPxSize);var k=Math.min(m,g);l=l.options.maxSize;if(e||!/%$/.test(l))a=v;else if(l=parseFloat(l),a=(k+f-a.h/2)*l/100/(l/100+1),c&&m-a>=g||!c&&g-a>=m)a=v;return[b,Math.ceil(a)]};b.prototype.updateRanges=function(b,a){var c=this.legend.options.bubbleLegend;c.minSize=b;c.maxSize=a;c.ranges=this.getRanges()};b.prototype.correctSizes=function(){var b=
this.legend,a=this.chart.series[this.options.seriesIndex].getPxExtremes();1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),b.render())};return b}()});x(c,"Series/Bubble/BubbleLegendComposition.js",[c["Series/Bubble/BubbleLegendDefaults.js"],c["Series/Bubble/BubbleLegendItem.js"],c["Core/DefaultOptions.js"],c["Core/Utilities.js"]],function(c,k,n,q){var r=n.setOptions,g=q.addEvent,f=q.objectEach,a=q.wrap,t;(function(m){function n(a,c,d){var l=
this.legend,g=0<=e(this);if(l&&l.options.enabled&&l.bubbleLegend&&l.options.bubbleLegend.autoRanges&&g){var h=l.bubbleLegend.options;g=l.bubbleLegend.predictBubbleSizes();l.bubbleLegend.updateRanges(g[0],g[1]);h.placed||(l.group.placed=!1,l.allItems.forEach(function(b){b.legendGroup.translateY=null}));l.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();h.placed||(b.setScale(),b.updateNames(),f(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});h.placed=!0;this.getMargins();
a.call(this,c,d);l.bubbleLegend.correctSizes();t(l,b(l))}else a.call(this,c,d),l&&l.options.enabled&&l.bubbleLegend&&(l.render(),t(l,b(l)))}function e(b){b=b.series;for(var a=0;a<b.length;){if(b[a]&&b[a].isBubble&&b[a].visible&&b[a].zData.length)return a;a++}return-1}function b(b){b=b.allItems;var a=[],c=b.length,e,d=0;for(e=0;e<c;e++)if(b[e].legendItemHeight&&(b[e].itemHeight=b[e].legendItemHeight),b[e]===b[c-1]||b[e+1]&&b[e]._legendItemPos[1]!==b[e+1]._legendItemPos[1]){a.push({height:0});var f=
a[a.length-1];for(d;d<=e;d++)b[d].itemHeight>f.height&&(f.height=b[d].itemHeight);f.step=e}return a}function d(b){var a=this.bubbleLegend,c=this.options,d=c.bubbleLegend,f=e(this.chart);a&&a.ranges&&a.ranges.length&&(d.ranges.length&&(d.autoRanges=!!d.ranges[0].autoRanges),this.destroyItem(a));0<=f&&c.enabled&&d.enabled&&(d.seriesIndex=f,this.bubbleLegend=new k(d,this),this.bubbleLegend.addToLegend(b.allItems))}function p(){var b=this.chart,a=this.visible,c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=
!a,this.ignoreSeries=a,b=0<=e(b),c.bubbleLegend.visible!==b&&(c.update({bubbleLegend:{enabled:b}}),c.bubbleLegend.visible=b),this.visible=a)}function t(b,a){var c=b.options.rtl,e,d,f,g=0;b.allItems.forEach(function(b,l){e=b.legendGroup.translateX;d=b._legendItemPos[1];if((f=b.movementX)||c&&b.ranges)f=c?e-b.options.maxSize/2:e+f,b.legendGroup.attr({translateX:f});l>a[g].step&&g++;b.legendGroup.attr({translateY:Math.round(d+a[g].height/2)});b._legendItemPos[1]=d+a[g].height/2})}var q=[];m.compose=
function(b,e,f){-1===q.indexOf(b)&&(q.push(b),r({legend:{bubbleLegend:c}}),a(b.prototype,"drawChartBox",n));-1===q.indexOf(e)&&(q.push(e),g(e,"afterGetAllItems",d));-1===q.indexOf(f)&&(q.push(f),g(f,"legendItemClick",p))}})(t||(t={}));return t});x(c,"Series/Bubble/BubblePoint.js",[c["Core/Series/Point.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k,n){var q=this&&this.__extends||function(){var c=function(g,f){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,
c){a.__proto__=c}||function(a,c){for(var f in c)c.hasOwnProperty(f)&&(a[f]=c[f])};return c(g,f)};return function(g,f){function a(){this.constructor=g}c(g,f);g.prototype=null===f?Object.create(f):(a.prototype=f.prototype,new a)}}();n=n.extend;k=function(k){function g(){var c=null!==k&&k.apply(this,arguments)||this;c.options=void 0;c.series=void 0;return c}q(g,k);g.prototype.haloPath=function(f){return c.prototype.haloPath.call(this,0===f?0:(this.marker?this.marker.radius||0:0)+f)};return g}(k.seriesTypes.scatter.prototype.pointClass);
n(k.prototype,{ttBelow:!1});return k});x(c,"Series/Bubble/BubbleSeries.js",[c["Core/Axis/Axis.js"],c["Series/Bubble/BubbleLegendComposition.js"],c["Series/Bubble/BubblePoint.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Core/Series/Series.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k,n,q,r,g,f,a){var t=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&
(b[c]=a[c])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),m=q.parse;q=r.noop;var y=f.seriesTypes;r=y.column;var e=y.scatter;y=a.addEvent;var b=a.arrayMax,d=a.arrayMin,p=a.clamp,w=a.extend,z=a.isNumber,h=a.merge,u=a.pick;a=function(a){function c(){var b=null!==a&&a.apply(this,arguments)||this;b.data=void 0;b.maxPxSize=void 0;b.minPxSize=void 0;b.options=void 0;b.points=void 0;b.radii=void 0;b.yData=
void 0;b.zData=void 0;return b}t(c,a);c.prototype.animate=function(b){!b&&this.points.length<this.options.animationLimit&&this.points.forEach(function(b){var a=b.graphic;a&&a.width&&(this.hasRendered||a.attr({x:b.plotX,y:b.plotY,width:1,height:1}),a.animate(this.markerAttribs(b),this.options.animation))},this)};c.prototype.getRadii=function(){var b=this,a=this.zData,c=this.yData,e=[],d=this.chart.bubbleZExtremes;var f=this.getPxExtremes();var l=f.minPxSize,g=f.maxPxSize;if(!d){var m=Number.MAX_VALUE,
h=-Number.MAX_VALUE,k;this.chart.series.forEach(function(a){a.bubblePadding&&(a.visible||!b.chart.options.chart.ignoreHiddenSeries)&&(a=a.getZExtremes())&&(m=Math.min(m||a.zMin,a.zMin),h=Math.max(h||a.zMax,a.zMax),k=!0)});k?(d={zMin:m,zMax:h},this.chart.bubbleZExtremes=d):d={zMin:0,zMax:0}}var p=0;for(f=a.length;p<f;p++){var n=a[p];e.push(this.getRadius(d.zMin,d.zMax,l,g,n,c[p]))}this.radii=e};c.prototype.getRadius=function(b,a,c,e,d,f){var l=this.options,g="width"!==l.sizeBy,m=l.zThreshold,h=a-b,
k=.5;if(null===f||null===d)return null;if(z(d)){l.sizeByAbsoluteValue&&(d=Math.abs(d-m),h=Math.max(a-m,Math.abs(b-m)),b=0);if(d<b)return c/2-1;0<h&&(k=(d-b)/h)}g&&0<=k&&(k=Math.sqrt(k));return Math.ceil(c+k*(e-c))/2};c.prototype.hasData=function(){return!!this.processedXData.length};c.prototype.pointAttribs=function(b,a){var c=this.options.marker.fillOpacity;b=g.prototype.pointAttribs.call(this,b,a);1!==c&&(b.fill=m(b.fill).setOpacity(c).get("rgba"));return b};c.prototype.translate=function(){a.prototype.translate.call(this);
this.getRadii();this.translateBubble()};c.prototype.translateBubble=function(){for(var b=this.data,a=this.radii,c=this.getPxExtremes().minPxSize,d=b.length;d--;){var e=b[d],f=a?a[d]:0;z(f)&&f>=c/2?(e.marker=w(e.marker,{radius:f,width:2*f,height:2*f}),e.dlBox={x:e.plotX-f,y:e.plotY-f,width:2*f,height:2*f}):e.shapeArgs=e.plotY=e.dlBox=void 0}};c.prototype.getPxExtremes=function(){var b=Math.min(this.chart.plotWidth,this.chart.plotHeight),a=function(a){if("string"===typeof a){var c=/%$/.test(a);a=parseInt(a,
10)}return c?b*a/100:a},c=a(u(this.options.minSize,8));a=Math.max(a(u(this.options.maxSize,"20%")),c);return{minPxSize:c,maxPxSize:a}};c.prototype.getZExtremes=function(){var a=this.options,c=(this.zData||[]).filter(z);if(c.length){var e=u(a.zMin,p(d(c),!1===a.displayNegative?a.zThreshold||0:-Number.MAX_VALUE,Number.MAX_VALUE));a=u(a.zMax,b(c));if(z(e)&&z(a))return{zMin:e,zMax:a}}};c.compose=k.compose;c.defaultOptions=h(e.defaultOptions,{dataLabels:{formatter:function(){var b=this.series.chart.numberFormatter,
a=this.point.z;return z(a)?b(a,-1):""},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"});return c}(e);w(a.prototype,{alignDataLabel:r.prototype.alignDataLabel,applyZones:q,bubblePadding:!0,buildKDTree:q,directTouch:!0,
isBubble:!0,pointArrayMap:["y","z"],pointClass:n,parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",zoneAxis:"z"});y(a,"updatedData",function(b){delete b.target.chart.bubbleZExtremes});c.prototype.beforePadding=function(){var b=this,a=this.len,c=this.chart,e=0,d=a,f=this.isXAxis,g=f?"xData":"yData",m=this.min,h=this.max-m,k=a/h,p;this.series.forEach(function(a){if(a.bubblePadding&&(a.visible||!c.options.chart.ignoreHiddenSeries)){p=b.allowZoomOutside=!0;var l=
a[g];f&&a.getRadii(0,0,a);if(0<h)for(var n=l.length;n--;)if(z(l[n])&&b.dataMin<=l[n]&&l[n]<=b.max){var u=a.radii&&a.radii[n]||0;e=Math.min((l[n]-m)*k-u,e);d=Math.max((l[n]-m)*k+u,d)}}});p&&0<h&&!this.logarithmic&&(d-=a,k*=(a+Math.max(0,e)-Math.min(d,a))/a,[["min","userMin",e],["max","userMax",d]].forEach(function(a){"undefined"===typeof u(b.options[a[0]],b[a[1]])&&(b[a[0]]+=a[2]/k)}))};f.registerSeriesType("bubble",a);"";"";return a});x(c,"Series/MapBubble/MapBubblePoint.js",[c["Core/Series/SeriesRegistry.js"],
c["Core/Utilities.js"]],function(c,k){var n=this&&this.__extends||function(){var c=function(f,a){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var f in c)c.hasOwnProperty(f)&&(a[f]=c[f])};return c(f,a)};return function(f,a){function g(){this.constructor=f}c(f,a);f.prototype=null===a?Object.create(a):(g.prototype=a.prototype,new g)}}();c=c.seriesTypes;var q=c.map,r=k.merge;return function(c){function f(){return null!==c&&c.apply(this,arguments)||
this}n(f,c);f.prototype.applyOptions=function(a,f){return a&&"undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?c.prototype.applyOptions.call(this,r(a,this.series.chart.fromLatLonToPoint(a)),f):q.prototype.pointClass.prototype.applyOptions.call(this,a,f)};f.prototype.isValid=function(){return"number"===typeof this.z};return f}(c.bubble.prototype.pointClass)});x(c,"Series/MapBubble/MapBubbleSeries.js",[c["Series/Bubble/BubbleSeries.js"],c["Series/MapBubble/MapBubblePoint.js"],c["Series/Map/MapSeries.js"],
c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k,n,q,r){var g=this&&this.__extends||function(){var a=function(c,e){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return a(c,e)};return function(c,e){function b(){this.constructor=c}a(c,e);c.prototype=null===e?Object.create(e):(b.prototype=e.prototype,new b)}}(),f=q.seriesTypes.mappoint,a=r.extend,t=r.merge;r=function(a){function m(){var c=
null!==a&&a.apply(this,arguments)||this;c.data=void 0;c.options=void 0;c.points=void 0;return c}g(m,a);m.prototype.translate=function(){f.prototype.translate.call(this);this.getRadii();this.translateBubble()};m.compose=c.compose;m.defaultOptions=t(c.defaultOptions,{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}});return m}(c);a(r.prototype,{type:"mapbubble",axisTypes:["colorAxis"],getProjectedBounds:n.prototype.getProjectedBounds,isCartesian:!1,pointArrayMap:["z"],pointClass:k,
processData:n.prototype.processData,setData:n.prototype.setData,setOptions:n.prototype.setOptions,useMapGeometry:!0,xyFromShape:!0});q.registerSeriesType("mapbubble",r);"";return r});x(c,"Series/Heatmap/HeatmapPoint.js",[c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,k){var n=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};
return a(c,f)};return function(c,f){function g(){this.constructor=c}a(c,f);c.prototype=null===f?Object.create(f):(g.prototype=f.prototype,new g)}}(),q=k.clamp,r=k.defined,g=k.extend,f=k.pick;c=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.options=void 0;c.series=void 0;c.value=void 0;c.x=void 0;c.y=void 0;return c}n(c,a);c.prototype.applyOptions=function(c,f){c=a.prototype.applyOptions.call(this,c,f);c.formatPrefix=c.isNull||null===c.value?"null":"point";return c};c.prototype.getCellAttributes=
function(){var a=this.series,c=a.options,e=(c.colsize||1)/2,b=(c.rowsize||1)/2,d=a.xAxis,g=a.yAxis,k=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var n=f(this.pointPadding,c.pointPadding,0),h={x1:q(Math.round(d.len-(d.translate(this.x-e,!1,!0,!1,!0,-a)||0)),-d.len,2*d.len),x2:q(Math.round(d.len-(d.translate(this.x+e,!1,!0,!1,!0,-a)||0)),-d.len,2*d.len),y1:q(Math.round(g.translate(this.y-b,!1,!0,!1,!0)||0),-g.len,2*g.len),y2:q(Math.round(g.translate(this.y+b,!1,!0,!1,!0)||0),
-g.len,2*g.len)};[["width","x"],["height","y"]].forEach(function(b){var a=b[0];b=b[1];var c=b+"1",e=b+"2",d=Math.abs(h[c]-h[e]),f=k&&k.lineWidth||0,g=Math.abs(h[c]+h[e])/2;a=k&&k[a];r(a)&&a<d&&(a=a/2+f/2,h[c]=g-a,h[e]=g+a);n&&("y"===b&&(c=e,e=b+"1"),h[c]+=n,h[e]-=n)});return h};c.prototype.haloPath=function(a){if(!a)return[];var c=this.shapeArgs;return["M",c.x-a,c.y-a,"L",c.x-a,c.y+c.height+a,c.x+c.width+a,c.y+c.height+a,c.x+c.width+a,c.y-a,"Z"]};c.prototype.isValid=function(){return Infinity!==this.value&&
-Infinity!==this.value};return c}(c.seriesTypes.scatter.prototype.pointClass);g(c.prototype,{dataLabelOnNull:!0,moveToTopOnHover:!0,ttBelow:!1});return c});x(c,"Series/Heatmap/HeatmapSeries.js",[c["Core/Color/Color.js"],c["Series/ColorMapMixin.js"],c["Series/Heatmap/HeatmapPoint.js"],c["Core/Legend/LegendSymbol.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,k,n,q,r,g,f){var a=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return b(a,c)};return function(a,c){function e(){this.constructor=a}b(a,c);a.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),t=r.series,m=r.seriesTypes,x=m.column,e=m.scatter,b=g.prototype.symbols,d=f.extend,p=f.fireEvent,w=f.isNumber,z=f.merge,h=f.pick;g=function(f){function g(){var b=null!==f&&f.apply(this,arguments)||this;b.colorAxis=void 0;b.data=
void 0;b.options=void 0;b.points=void 0;b.valueMax=NaN;b.valueMin=NaN;return b}a(g,f);g.prototype.drawPoints=function(){var b=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)t.prototype.drawPoints.call(this),this.points.forEach(function(a){a.graphic&&(a.graphic[b.chart.styledMode?"css":"animate"](b.colorAttribs(a)),b.options.borderRadius&&a.graphic.attr({r:b.options.borderRadius}),(a.shapeArgs||{}).r=b.options.borderRadius,(a.shapeArgs||{}).d=a.graphic.pathArray,null===a.value&&a.graphic.addClass("highcharts-null-point"))})};
g.prototype.getExtremes=function(){var b=t.prototype.getExtremes.call(this,this.valueData),a=b.dataMin;b=b.dataMax;w(a)&&(this.valueMin=a);w(b)&&(this.valueMax=b);return t.prototype.getExtremes.call(this)};g.prototype.getValidPoints=function(b,a){return t.prototype.getValidPoints.call(this,b,a,!0)};g.prototype.hasData=function(){return!!this.processedXData.length};g.prototype.init=function(){t.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=h(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=
a.rowsize||1;b.ellipse=b.circle};g.prototype.markerAttribs=function(b,a){var c=b.marker||{},e=this.options.marker||{},d=b.shapeArgs||{},f={};if(b.hasImage)return{x:b.plotX,y:b.plotY};if(a){var g=e.states[a]||{};var l=c.states&&c.states[a]||{};[["width","x"],["height","y"]].forEach(function(b){f[b[0]]=(l[b[0]]||g[b[0]]||d[b[0]])+(l[b[0]+"Plus"]||g[b[0]+"Plus"]||0);f[b[1]]=d[b[1]]+(d[b[0]]-f[b[0]])/2})}return a?f:d};g.prototype.pointAttribs=function(b,a){var e=t.prototype.pointAttribs.call(this,b,a),
d=this.options||{},f=this.chart.options.plotOptions||{},g=f.series||{},h=f.heatmap||{};f=b&&b.options.borderColor||d.borderColor||h.borderColor||g.borderColor;g=b&&b.options.borderWidth||d.borderWidth||h.borderWidth||g.borderWidth||e["stroke-width"];e.stroke=b&&b.marker&&b.marker.lineColor||d.marker&&d.marker.lineColor||f||this.color;e["stroke-width"]=g;a&&(b=z(d.states[a],d.marker&&d.marker.states[a],b&&b.options.states&&b.options.states[a]||{}),a=b.brightness,e.fill=b.color||c.parse(e.fill).brighten(a||
0).get(),e.stroke=b.lineColor);return e};g.prototype.setClip=function(b){var a=this.chart;t.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||b)&&this.markerGroup.clip((b||this.clipBox)&&this.sharedClipKey?a.sharedClips[this.sharedClipKey]:a.clipRect)};g.prototype.translate=function(){var a=this.options,c=a.marker&&a.marker.symbol||"rect",e=b[c]?c:"rect",f=-1!==["circle","square"].indexOf(e);this.generatePoints();this.points.forEach(function(a){var g=a.getCellAttributes(),h={};h.x=
Math.min(g.x1,g.x2);h.y=Math.min(g.y1,g.y2);h.width=Math.max(Math.abs(g.x2-g.x1),0);h.height=Math.max(Math.abs(g.y2-g.y1),0);var k=a.hasImage=0===(a.marker&&a.marker.symbol||c||"").indexOf("url");if(f){var l=Math.abs(h.width-h.height);h.x=Math.min(g.x1,g.x2)+(h.width<h.height?0:l/2);h.y=Math.min(g.y1,g.y2)+(h.width<h.height?l/2:0);h.width=h.height=Math.min(h.width,h.height)}l={plotX:(g.x1+g.x2)/2,plotY:(g.y1+g.y2)/2,clientX:(g.x1+g.x2)/2,shapeType:"path",shapeArgs:z(!0,h,{d:b[e](h.x,h.y,h.width,h.height)})};
k&&(a.marker={width:h.width,height:h.height});d(a,l)});p(this,"afterTranslate")};g.defaultOptions=z(e.defaultOptions,{animation:!1,borderRadius:0,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){var b=this.series.chart.numberFormatter,a=this.point.value;return w(a)?b(a,-1):""},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},
states:{hover:{halo:!1,brightness:.2}}});return g}(e);d(g.prototype,{alignDataLabel:x.prototype.alignDataLabel,axisTypes:k.SeriesMixin.axisTypes,colorAttribs:k.SeriesMixin.colorAttribs,colorKey:k.SeriesMixin.colorKey,directTouch:!0,drawLegendSymbol:q.drawRectangle,getExtremesFromAll:!0,getSymbol:t.prototype.getSymbol,parallelArrays:k.SeriesMixin.parallelArrays,pointArrayMap:["y","value"],pointClass:n,trackerGroups:k.SeriesMixin.trackerGroups});r.registerSeriesType("heatmap",g);"";"";return g});x(c,
"Extensions/GeoJSON.js",[c["Core/Chart/Chart.js"],c["Core/FormatUtilities.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,k,n,q){function r(a,b){var c,e=!1,f=a.x,g=a.y;a=0;for(c=b.length-1;a<b.length;c=a++){var h=b[a][1]>g;var k=b[c][1]>g;h!==k&&f<(b[c][0]-b[a][0])*(g-b[a][1])/(b[c][1]-b[a][1])+b[a][0]&&(e=!e)}return e}var g=k.format,f=n.win,a=q.error,t=q.extend,m=q.merge;k=q.wrap;"";c.prototype.transformFromLatLon=function(c,b){var d=this.options.chart.proj4||f.proj4;if(!d)return a(21,
!1,this),{x:0,y:null};var e=b.jsonmarginX;e=void 0===e?0:e;var g=b.jsonmarginY;g=void 0===g?0:g;var k=b.jsonres;k=void 0===k?1:k;var h=b.scale;h=void 0===h?1:h;var m=b.xoffset;m=void 0===m?0:m;var n=b.xpan;n=void 0===n?0:n;var l=b.yoffset;l=void 0===l?0:l;var q=b.ypan;q=void 0===q?0:q;c=d(b.crs,[c.lon,c.lat]);d=b.cosAngle||b.rotation&&Math.cos(b.rotation);var r=b.sinAngle||b.rotation&&Math.sin(b.rotation);b=b.rotation?[c[0]*d+c[1]*r,-c[0]*r+c[1]*d]:c;return{x:((b[0]-m)*h+n)*k+e,y:-(((l-b[1])*h+q)*
k-g)}};c.prototype.transformToLatLon=function(c,b){if(!this.options.chart.proj4&&!f.proj4)a(21,!1,this);else if(null!==c.y){var d=b.jsonmarginX,e=b.jsonmarginY,g=b.jsonres;g=void 0===g?1:g;var k=b.scale;k=void 0===k?1:k;var h=b.xoffset,m=b.xpan,n=b.yoffset,l=b.ypan;c={x:((c.x-(void 0===d?0:d))/g-(void 0===m?0:m))/k+(void 0===h?0:h),y:((c.y-(void 0===e?0:e))/g+(void 0===l?0:l))/k+(void 0===n?0:n)};d=b.cosAngle||b.rotation&&Math.cos(b.rotation);e=b.sinAngle||b.rotation&&Math.sin(b.rotation);b=f.proj4(b.crs,
"WGS84",b.rotation?{x:c.x*d+c.y*-e,y:c.x*e+c.y*d}:c);return{lat:b.y,lon:b.x}}};c.prototype.fromPointToLatLon=function(c){var b=this.mapTransforms;if(b){for(var d in b)if(Object.hasOwnProperty.call(b,d)&&b[d].hitZone&&r(c,b[d].hitZone.coordinates[0]))return this.transformToLatLon(c,b[d]);return this.transformToLatLon(c,b["default"])}a(22,!1,this)};c.prototype.fromLatLonToPoint=function(c){var b=this.mapTransforms,d;if(!b)return a(22,!1,this),{x:0,y:null};for(d in b)if(Object.hasOwnProperty.call(b,
d)&&b[d].hitZone){var e=this.transformFromLatLon(c,b[d]);if(r(e,b[d].hitZone.coordinates[0]))return e}return this.transformFromLatLon(c,b["default"])};var x=function(a,b){b||(b=Object.keys(a.objects)[0]);b=a.objects[b];if(b["hc-decoded-geojson"])return b["hc-decoded-geojson"];var c=a.arcs;if(a.transform){var e=a.transform,f=e.scale,g=e.translate;c=a.arcs.map(function(b){var a=0,c=0;return b.map(function(b){b=b.slice();b[0]=(a+=b[0])*f[0]+g[0];b[1]=(c+=b[1])*f[1]+g[1];return b})})}var h=function(b){return"number"===
typeof b[0]?b.reduce(function(b,a,d){return b.concat((0>a?c[~a].reverse():c[a]).slice(0===d?0:1))},[]):b.map(h)};e=b.geometries.map(function(b){return{type:"Feature",properties:b.properties,geometry:{type:b.type,coordinates:b.coordinates||h(b.arcs)}}});a={type:"FeatureCollection",copyright:a.copyright,copyrightShort:a.copyrightShort,copyrightUrl:a.copyrightUrl,features:e};return b["hc-decoded-geojson"]=a};n.geojson=function(a,b,c){void 0===b&&(b="map");var d=[];a="Topology"===a.type?x(a):a;a.features.forEach(function(a){var c=
a.geometry||{},e=c.type;c=c.coordinates;a=a.properties;var f;"map"!==b&&"mapbubble"!==b||"Polygon"!==e&&"MultiPolygon"!==e?"mapline"!==b||"LineString"!==e&&"MultiLineString"!==e?"mappoint"===b&&"Point"===e&&c.length&&(f={geometry:{coordinates:c,type:e}}):c.length&&(f={geometry:{coordinates:c,type:e}}):c.length&&(f={geometry:{coordinates:c,type:e}});f&&(e=a&&(a.name||a.NAME),d.push(t(f,{name:"string"===typeof e?e:void 0,properties:a})))});c&&a.copyrightShort&&(c.chart.mapCredits=g(c.chart.options.credits.mapText,
{geojson:a}),c.chart.mapCreditsFull=g(c.chart.options.credits.mapTextFull,{geojson:a}));return d};k(c.prototype,"addCredits",function(a,b){b=m(!0,this.options.credits,b);this.mapCredits&&(b.href=null);a.call(this,b);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});x(c,"masters/modules/map.src.js",[c["Core/Globals.js"],c["Core/Axis/Color/ColorAxis.js"],c["Series/MapBubble/MapBubbleSeries.js"],c["Core/Chart/MapChart.js"]],function(c,k,n,q){c.ColorAxis=k;c.MapChart=
q;c.mapChart=c.Map=q.mapChart;c.maps=q.maps;k.compose(c.Chart,c.Fx,c.Legend,c.Series);n.compose(c.Chart,c.Legend,c.Series)})});
//# sourceMappingURL=map.js.map