/*
 Highcharts JS v9.3.2 (2021-12-20)

 (c) 2016-2021 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/sunburst",["highcharts"],function(v){a(v);a.Highcharts=v;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function v(a,h,d,t){a.hasOwnProperty(h)||(a[h]=t.apply(null,d))}a=a?a._modules:{};v(a,"Series/ColorMapMixin.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,h,d){var t=
a.noop;a=a.seriesTypes;var p=d.defined;d=d.addEvent;d(h,"afterSetState",function(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})});return{PointMixin:{dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value}},SeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:t,parallelArrays:["x","y","value"],
colorKey:"value",pointAttribs:a.column.prototype.pointAttribs,colorAttribs:function(a){var q={};!p(a.color)||a.state&&"normal"!==a.state||(q[this.colorProp||"fill"]=a.color);return q}}}});v(a,"Series/Treemap/TreemapAlgorithmGroup.js",[],function(){return function(){function a(a,d,t,p){this.height=a;this.width=d;this.plot=p;this.startDirection=this.direction=t;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,k){return Math.max(a/
k,k/a)}}}a.prototype.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,
this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};a.prototype.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0};return a}()});v(a,"Series/DrawPointComposition.js",[],function(){var a;(function(a){function d(a){var k=this,e=a.animatableAttribs,d=a.onComplete,c=a.css,b=a.renderer,B=this.series&&this.series.chart.hasRendered?void 0:this.series&&this.series.options.animation,m=this.graphic;a.attribs=a.attribs||{};a.attribs["class"]=this.getClassName();if(this.shouldDraw())m||
(this.graphic=m=b[a.shapeType](a.shapeArgs).add(a.group)),m.css(c).attr(a.attribs).animate(e,a.isNew?!1:B,d);else if(m){var g=function(){k.graphic=m=m&&m.destroy();"function"===typeof d&&d()};Object.keys(e).length?m.animate(e,void 0,function(){g()}):g()}}function h(){return!this.isNull}var p=[];a.compose=function(a){if(-1===p.indexOf(a)){p.push(a);var k=a.prototype;k.draw=d;k.shouldDraw||(k.shouldDraw=h)}return a}})(a||(a={}));return a});v(a,"Series/Treemap/TreemapPoint.js",[a["Series/DrawPointComposition.js"],
a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,h,d){var t=this&&this.__extends||function(){var a=function(c,B){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,g){a.__proto__=g}||function(a,g){for(var c in g)g.hasOwnProperty(c)&&(a[c]=g[c])};return a(c,B)};return function(c,B){function b(){this.constructor=c}a(c,B);c.prototype=null===B?Object.create(B):(b.prototype=B.prototype,new b)}}(),p=h.series.prototype.pointClass,q=h.seriesTypes;h=q.pie.prototype.pointClass;
var k=d.extend,e=d.isNumber,u=d.pick;d=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.name=void 0;c.node=void 0;c.options=void 0;c.series=void 0;c.value=void 0;return c}t(c,a);c.prototype.getClassName=function(){var a=p.prototype.getClassName.call(this),c=this.series,g=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||u(g.interactByLeaf,!g.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";
return a};c.prototype.isValid=function(){return!(!this.id&&!e(this.value))};c.prototype.setState=function(a){p.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})};c.prototype.shouldDraw=function(){return e(this.plotY)&&null!==this.y};return c}(q.scatter.prototype.pointClass);k(d.prototype,{setVisible:h.prototype.setVisible});a.compose(d);return d});v(a,"Series/Treemap/TreemapUtilities.js",[a["Core/Utilities.js"]],function(a){var h=a.objectEach,d;(function(a){function d(a,
k,e){void 0===e&&(e=this);a=k.call(e,a);!1!==a&&d(a,k,e)}a.AXIS_MAX=100;a.isBoolean=function(a){return"boolean"===typeof a};a.eachObject=function(a,d,e){e=e||this;h(a,function(k,c){d.call(e,k,c,a)})};a.recursive=d})(d||(d={}));return d});v(a,"Series/TreeUtilities.js",[a["Core/Color/Color.js"],a["Core/Utilities.js"]],function(a,h){function d(a,b){var c=b.before,m=b.idRoot,g=b.mapIdToNode[m],C=b.points[a.i],k=C&&C.options||{},z=[],e=0;a.levelDynamic=a.level-(!1!==b.levelIsConstant?0:g.level);a.name=
u(C&&C.name,"");a.visible=m===a.id||!0===b.visible;"function"===typeof c&&(a=c(a,b));a.children.forEach(function(g,c){var m=t({},b);t(m,{index:c,siblings:a.children.length,visible:a.visible});g=d(g,m);z.push(g);g.visible&&(e+=g.val)});c=u(k.value,e);a.visible=0<=c&&(0<e||a.visible);a.children=z;a.childrenTotal=e;a.isLeaf=a.visible&&!e;a.val=c;return a}var t=h.extend,p=h.isArray,q=h.isNumber,k=h.isObject,e=h.merge,u=h.pick;return{getColor:function(c,b){var d=b.index,m=b.mapOptionsToLevel,g=b.parentColor,
C=b.parentColorIndex,e=b.series,z=b.colors,k=b.siblings,h=e.points,p=e.chart.options.chart,w;if(c){h=h[c.i];c=m[c.level]||{};if(m=h&&c.colorByPoint){var t=h.index%(z?z.length:p.colorCount);var q=z&&z[t]}if(!e.chart.styledMode){z=h&&h.options.color;p=c&&c.color;if(w=g)w=(w=c&&c.colorVariation)&&"brightness"===w.key&&d&&k?a.parse(g).brighten(d/k*w.to).get():g;w=u(z,p,q,w,e.color)}var F=u(h&&h.options.colorIndex,c&&c.colorIndex,t,C,b.colorIndex)}return{color:w,colorIndex:F}},getLevelOptions:function(a){var c=
null;if(k(a)){c={};var d=q(a.from)?a.from:1;var m=a.levels;var g={};var C=k(a.defaults)?a.defaults:{};p(m)&&(g=m.reduce(function(a,g){if(k(g)&&q(g.level)){var c=e({},g);var b=u(c.levelIsConstant,C.levelIsConstant);delete c.levelIsConstant;delete c.level;g=g.level+(b?0:d-1);k(a[g])?e(!0,a[g],c):a[g]=c}return a},{}));m=q(a.to)?a.to:1;for(a=0;a<=m;a++)c[a]=e({},C,k(g[a])?g[a]:{})}return c},setTreeValues:d,updateRootId:function(a){if(k(a)){var c=k(a.options)?a.options:{};c=u(a.rootNode,c.rootId,"");k(a.userOptions)&&
(a.userOptions.rootId=c);a.rootNode=c}return c}}});v(a,"Extensions/Breadcrumbs.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/DefaultOptions.js"],a["Core/Utilities.js"],a["Core/FormatUtilities.js"]],function(a,h,d,t,p){var q=p.format;p=t.addEvent;var k=t.objectEach,e=t.extend,u=t.fireEvent,c=t.merge,b=t.pick,B=t.defined;e(d.defaultOptions.lang,{mainBreadcrumb:"Main"});d=function(){function a(g,b){this.group=void 0;this.list=[];this.elementList={};this.isDirty=!0;this.level=0;this.options=
void 0;b=c(g.options.drilldown&&g.options.drilldown.drillUpButton,a.defaultBreadcrumbsOptions,b);this.chart=g;this.options=b||{}}a.prototype.updateProperties=function(a){this.setList(a);this.setLevel();this.isDirty=!0};a.prototype.setList=function(a){this.list=a};a.prototype.setLevel=function(){this.level=this.list.length&&this.list.length-1};a.prototype.getLevel=function(){return this.level};a.prototype.getButtonText=function(a){var g=this.chart,c=this.options,d=g.options.lang,e=b(c.format,c.showFullPath?
"{level.name}":"\u2190 {level.name}");d=d&&b(d.drillUpText,d.mainBreadcrumb);a=c.formatter&&c.formatter(a)||q(e,{level:a.levelOptions},g)||"";"\u2190 "===a&&B(d)&&(a=c.showFullPath?d:"\u2190 "+d);return a};a.prototype.redraw=function(){this.isDirty&&this.render();this.group&&this.group.align();this.isDirty=!1};a.prototype.render=function(){var a=this.chart,c=this.options;!this.group&&c&&(this.group=a.renderer.g("breadcrumbs-group").addClass("highcharts-no-tooltip highcharts-breadcrumbs").attr({zIndex:c.zIndex}).add());
c.showFullPath?this.renderFullPathButtons():this.renderSingleButton();this.alignBreadcrumbsGroup()};a.prototype.renderFullPathButtons=function(){this.destroySingleButton();this.resetElementListState();this.updateListElements();this.destroyListElements()};a.prototype.renderSingleButton=function(){var a=this.chart,c=this.list,b=this.options.buttonSpacing;this.destroyListElements();var d=this.group?this.group.getBBox().width:b;c=c[c.length-2];!a.drillUpButton&&0<this.level?a.drillUpButton=this.renderButton(c,
d,b):a.drillUpButton&&(0<this.level?this.updateSingleButton():this.destroySingleButton())};a.prototype.alignBreadcrumbsGroup=function(a){if(this.group){var g=this.options,d=g.buttonTheme,e=g.position,k="chart"===g.relativeTo||"spacingBox"===g.relativeTo?void 0:"scrollablePlotBox",m=this.group.getBBox();g=2*(d.padding||0)+g.buttonSpacing;e.width=m.width+g;e.height=m.height+g;e=c(e);a&&(e.x+=a);e.y=b(e.y,this.yOffset,0);this.group.align(e,!0,k)}};a.prototype.renderButton=function(a,b,d){var g=this,
e=this.chart,k=g.options,m=c(k.buttonTheme),h=m.states;delete m.states;b=e.renderer.button(g.getButtonText(a),b,d,function(c){var b=k.events&&k.events.click,e;b&&(e=b.call(g,c,a));!1!==e&&(c.newLevel=k.showFullPath?a.level:g.level-1,u(g,"up",c))},m,h&&h.hover,h&&h.select,h&&h.disabled).addClass("highcharts-breadcrumbs-button").add(g.group);e.styledMode||b.attr(k.style);return b};a.prototype.renderSeparator=function(a,c){var g=this.chart,b=this.options.separator;a=g.renderer.label(b.text,a,c,void 0,
void 0,void 0,!1).addClass("highcharts-breadcrumbs-separator").add(this.group);g.styledMode||a.css(b.style);return a};a.prototype.update=function(a){c(!0,this.options,a);this.destroy();this.isDirty=!0};a.prototype.updateSingleButton=function(){var a=this.chart,c=this.list[this.level-1];a.drillUpButton&&a.drillUpButton.attr({text:this.getButtonText(c)})};a.prototype.destroy=function(){this.destroySingleButton();this.destroyListElements(!0);this.group&&this.group.destroy();this.group=void 0};a.prototype.destroyListElements=
function(a){var c=this.elementList;k(c,function(g,b){if(a||!c[b].updated)g=c[b],g.button&&g.button.destroy(),g.separator&&g.separator.destroy(),delete g.button,delete g.separator,delete c[b]});a&&(this.elementList={})};a.prototype.destroySingleButton=function(){this.chart.drillUpButton&&(this.chart.drillUpButton.destroy(),this.chart.drillUpButton=void 0)};a.prototype.resetElementListState=function(){k(this.elementList,function(a){a.updated=!1})};a.prototype.updateListElements=function(){var a=function(a,
c){return a.getBBox().width+c},c=this,b=c.elementList,e=c.options.buttonSpacing,d=c.list,k=c.group?a(c.group,e):e,m;d.forEach(function(g,h){h=h===d.length-1;if(b[g.level]){m=b[g.level];var u=m.button;m.separator||h?m.separator&&h&&(m.separator.destroy(),delete m.separator):(k+=e,m.separator=c.renderSeparator(k,e),k+=a(m.separator,e));b[g.level].updated=!0}else{u=c.renderButton(g,k,e);k+=a(u,e);if(!h){var p=c.renderSeparator(k,e);k+=a(p,e)}b[g.level]={button:u,separator:p,updated:!0}}u&&u.setState(h?
2:0)})};a.defaultBreadcrumbsOptions={buttonTheme:{fill:"none",height:18,padding:2,"stroke-width":0,zIndex:7,states:{select:{fill:"none"}},style:{color:"#335cad"}},buttonSpacing:5,floating:!1,format:void 0,relativeTo:"plotBox",position:{align:"left",verticalAlign:"top",x:0,y:void 0},separator:{text:"/",style:{color:"#666666"}},showFullPath:!0,style:{},useHTML:!1,zIndex:7};return a}();h.Breadcrumbs||(h.Breadcrumbs=d,p(a,"getMargins",function(){var a=this.breadcrumbs;if(a&&!a.options.floating&&a.level){var c=
a.options,b=c.buttonTheme;b=(b.height||0)+2*(b.padding||0)+c.buttonSpacing;c=c.position.verticalAlign;"bottom"===c?(this.marginBottom=(this.marginBottom||0)+b,a.yOffset=b):"middle"!==c?(this.plotTop+=b,a.yOffset=-b):a.yOffset=void 0}}),p(a,"redraw",function(){this.breadcrumbs&&this.breadcrumbs.redraw()}),p(a,"destroy",function(){this.breadcrumbs&&(this.breadcrumbs.destroy(),this.breadcrumbs=void 0)}),p(a,"afterShowResetZoom",function(){if(this.breadcrumbs){var a=this.resetZoomButton&&this.resetZoomButton.getBBox(),
c=this.breadcrumbs.options;a&&"right"===c.position.align&&"plotBox"===c.relativeTo&&this.breadcrumbs.alignBreadcrumbsGroup(-a.width-c.buttonSpacing)}}),p(a,"selection",function(a){!0===a.resetSelection&&this.breadcrumbs&&this.breadcrumbs.alignBreadcrumbsGroup()}));"";return d});v(a,"Series/Treemap/TreemapComposition.js",[a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapUtilities.js"],a["Core/Utilities.js"]],function(a,h,d){var t=d.addEvent,p=d.extend,q=!1;t(a.series,"afterBindAxes",function(){var a=
this.xAxis,e=this.yAxis;if(a&&e)if(this.is("treemap")){var d={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,minPadding:0,max:h.AXIS_MAX,maxPadding:0,startOnTick:!1,title:void 0,tickPositions:[]};p(e.options,d);p(a.options,d);q=!0}else q&&(e.setOptions(e.userOptions),a.setOptions(a.userOptions),q=!1)})});v(a,"Series/Treemap/TreemapSeries.js",[a["Core/Color/Color.js"],a["Series/ColorMapMixin.js"],a["Core/Globals.js"],a["Core/Legend/LegendSymbol.js"],a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapAlgorithmGroup.js"],
a["Series/Treemap/TreemapPoint.js"],a["Series/Treemap/TreemapUtilities.js"],a["Series/TreeUtilities.js"],a["Extensions/Breadcrumbs.js"],a["Core/Utilities.js"]],function(a,h,d,t,p,q,k,e,u,c,b){var B=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,f){a.__proto__=f}||function(a,f){for(var c in f)f.hasOwnProperty(c)&&(a[c]=f[c])};return a(c,f)};return function(c,f){function l(){this.constructor=c}a(c,f);c.prototype=null===f?Object.create(f):
(l.prototype=f.prototype,new l)}}(),m=a.parse;a=d.noop;var g=p.series;d=p.seriesTypes;var C=d.column,v=d.heatmap,z=d.scatter,J=u.getColor,K=u.getLevelOptions,F=u.updateRootId,w=b.addEvent,G=b.correctFloat,E=b.defined,H=b.error,I=b.extend,M=b.fireEvent,N=b.isArray,R=b.isObject,n=b.isString,A=b.merge,D=b.pick,S=b.stableSort;u=function(a){function b(){var f=null!==a&&a.apply(this,arguments)||this;f.axisRatio=void 0;f.data=void 0;f.mapOptionsToLevel=void 0;f.nodeMap=void 0;f.options=void 0;f.points=void 0;
f.rootNode=void 0;f.tree=void 0;f.level=void 0;return f}B(b,a);b.prototype.algorithmCalcPoints=function(a,c,b,g){var f,l,r,e,n=b.lW,d=b.lH,x=b.plot,k=0,h=b.elArr.length-1;if(c)n=b.nW,d=b.nH;else var m=b.elArr[b.elArr.length-1];b.elArr.forEach(function(a){if(c||k<h)0===b.direction?(f=x.x,l=x.y,r=n,e=a/r):(f=x.x,l=x.y,e=d,r=a/e),g.push({x:f,y:l,width:r,height:G(e)}),0===b.direction?x.y+=e:x.x+=r;k+=1});b.reset();0===b.direction?b.width-=n:b.height-=d;x.y=x.parent.y+(x.parent.height-b.height);x.x=x.parent.x+
(x.parent.width-b.width);a&&(b.direction=1-b.direction);c||b.addElement(m)};b.prototype.algorithmFill=function(a,b,c){var f=[],l,r=b.direction,g=b.x,e=b.y,n=b.width,d=b.height,k,h,m,A;c.forEach(function(c){l=c.val/b.val*b.height*b.width;k=g;h=e;0===r?(A=d,m=l/A,n-=m,g+=m):(m=n,A=l/m,d-=A,e+=A);f.push({x:k,y:h,width:m,height:A});a&&(r=1-r)});return f};b.prototype.algorithmLowAspectRatio=function(a,b,c){var f=[],l=this,r,g={x:b.x,y:b.y,parent:b},e=0,n=c.length-1,d=new q(b.height,b.width,b.direction,
g);c.forEach(function(c){r=c.val/b.val*b.height*b.width;d.addElement(r);d.lP.nR>d.lP.lR&&l.algorithmCalcPoints(a,!1,d,f,g);e===n&&l.algorithmCalcPoints(a,!0,d,f,g);e+=1});return f};b.prototype.alignDataLabel=function(a,b,c){var f=c.style;f&&!E(f.textOverflow)&&b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:f.width+="px"});C.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})};b.prototype.buildNode=function(a,
b,c,g,e){var f=this,l=[],r=f.points[b],n=0,d;(g[a]||[]).forEach(function(b){d=f.buildNode(f.points[b].id,b,c+1,g,a);n=Math.max(d.height+1,n);l.push(d)});b={id:a,i:b,children:l,height:n,level:c,parent:e,visible:!1};f.nodeMap[b.id]=b;r&&(r.node=b);return b};b.prototype.calculateChildrenAreas=function(a,b){var f=this,c=f.options,l=f.mapOptionsToLevel[a.level+1],g=D(f[l&&l.layoutAlgorithm]&&l.layoutAlgorithm,c.layoutAlgorithm),n=c.alternateStartingDirection,d=[];a=a.children.filter(function(a){return!a.ignore});
l&&l.layoutStartingDirection&&(b.direction="vertical"===l.layoutStartingDirection?0:1);d=f[g](b,a);a.forEach(function(a,c){c=d[c];a.values=A(c,{val:a.childrenTotal,direction:n?1-b.direction:b.direction});a.pointValues=A(c,{x:c.x/f.axisRatio,y:e.AXIS_MAX-c.y-c.height,width:c.width/f.axisRatio});a.children.length&&f.calculateChildrenAreas(a,a.values)})};b.prototype.createList=function(a){var f=this.chart,b=[];if(f.breadcrumbs){var c=0;b.push({level:c,levelOptions:f.series[0]});f=a.target.nodeMap[a.newRootId];
for(var g=[];f.parent||""===f.parent;)g.push(f),f=a.target.nodeMap[f.parent];g.reverse().forEach(function(a){b.push({level:++c,levelOptions:a})});1>=b.length&&(b.length=0)}return b};b.prototype.drawDataLabels=function(){var a=this,b=a.mapOptionsToLevel,c,e;a.points.filter(function(a){return a.node.visible}).forEach(function(f){e=b[f.node.level];c={style:{}};f.node.isLeaf||(c.enabled=!1);e&&e.dataLabels&&(c=A(c,e.dataLabels),a._hasPointLabels=!0);f.shapeArgs&&(c.style.width=f.shapeArgs.width,f.dataLabel&&
f.dataLabel.css({width:f.shapeArgs.width+"px"}));f.dlOptions=A(c,f.options.dataLabels)});g.prototype.drawDataLabels.call(this)};b.prototype.drawPoints=function(){var a=this,b=a.chart,c=b.renderer,g=b.styledMode,e=a.options,n=g?{}:e.shadow,d=e.borderRadius,k=b.pointCount<e.animationLimit,h=e.allowTraversingTree;a.points.forEach(function(f){var b=f.node.levelDynamic,l={},r={},O={},m="level-group-"+f.node.level,P=!!f.graphic,T=k&&P,x=f.shapeArgs;f.shouldDraw()&&(f.isInside=!0,d&&(r.r=d),A(!0,T?l:r,P?
x:{},g?{}:a.pointAttribs(f,f.selected?"select":void 0)),a.colorAttribs&&g&&I(O,a.colorAttribs(f)),a[m]||(a[m]=c.g(m).attr({zIndex:1E3-(b||0)}).add(a.group),a[m].survive=!0));f.draw({animatableAttribs:l,attribs:r,css:O,group:a[m],renderer:c,shadow:n,shapeArgs:x,shapeType:"rect"});h&&f.graphic&&(f.drillId=e.interactByLeaf?a.drillToByLeaf(f):a.drillToByGroup(f))})};b.prototype.drillToByGroup=function(a){var f=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(f=a.id);return f};b.prototype.drillToByLeaf=
function(a){var f=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!f;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(f=a.id);return f};b.prototype.drillToNode=function(a,b){H(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,b)};b.prototype.drillUp=function(){var a=this.nodeMap[this.rootNode];a&&n(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})};b.prototype.getExtremes=function(){var a=g.prototype.getExtremes.call(this,this.colorValueData),
b=a.dataMax;this.valueMin=a.dataMin;this.valueMax=b;return g.prototype.getExtremes.call(this)};b.prototype.getListOfParents=function(a,b){a=N(a)?a:[];var f=N(b)?b:[];b=a.reduce(function(a,f,b){f=D(f.parent,"");"undefined"===typeof a[f]&&(a[f]=[]);a[f].push(b);return a},{"":[]});e.eachObject(b,function(a,b,c){""!==b&&-1===f.indexOf(b)&&(a.forEach(function(a){c[""].push(a)}),delete c[b])});return b};b.prototype.getTree=function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,
a);this.nodeMap={};return this.buildNode("",-1,0,a)};b.prototype.hasData=function(){return!!this.processedXData.length};b.prototype.init=function(a,b){var f=this,e=A(b.drillUpButton,b.breadcrumbs);this.colorAttribs=h.SeriesMixin.colorAttribs;var d=w(f,"setOptions",function(a){a=a.userOptions;E(a.allowDrillToNode)&&!E(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);E(a.drillUpButton)&&!E(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});
g.prototype.init.call(f,a,b);delete f.opacity;f.eventsToUnbind.push(d);f.options.allowTraversingTree&&(f.eventsToUnbind.push(w(f,"click",f.onClickDrillToNode)),f.eventsToUnbind.push(w(f,"setRootNode",function(a){var b=f.chart;b.breadcrumbs&&b.breadcrumbs.updateProperties(f.createList(a))})),f.eventsToUnbind.push(w(f,"update",function(a,f){(f=this.chart.breadcrumbs)&&a.options.breadcrumbs&&f.update(a.options.breadcrumbs)})),f.eventsToUnbind.push(w(f,"destroy",function(a){var f=this.chart;f.breadcrumbs&&
(f.breadcrumbs.destroy(),a.keepEventsForUpdate||(f.breadcrumbs=void 0))})));a.breadcrumbs||(a.breadcrumbs=new c(a,e));f.eventsToUnbind.push(w(a.breadcrumbs,"up",function(a){a=this.level-a.newLevel;for(var b=0;b<a;b++)f.drillUp()}))};b.prototype.onClickDrillToNode=function(a){var f=(a=a.point)&&a.drillId;n(f)&&(a.setState(""),this.setRootNode(f,!0,{trigger:"click"}))};b.prototype.pointAttribs=function(a,b){var f=R(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},c=a&&f[a.node.level]||{};f=this.options;
var g=b&&f.states[b]||{},e=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||c.borderColor||g.borderColor||f.borderColor,"stroke-width":D(a&&a.borderWidth,c.borderWidth,g.borderWidth,f.borderWidth),dashstyle:a&&a.borderDashStyle||c.borderDashStyle||g.borderDashStyle||f.borderDashStyle,fill:a&&a.color||this.color};-1!==e.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==e.indexOf("highcharts-internal-node-interactive")?(b=D(g.opacity,f.opacity),a.fill=m(a.fill).setOpacity(b).get(),
a.cursor="pointer"):-1!==e.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=m(a.fill).brighten(g.brightness).get());return a};b.prototype.setColorRecursive=function(a,b,c,g,e){var f=this,d=f&&f.chart;d=d&&d.options&&d.options.colors;if(a){var n=J(a,{colors:d,index:g,mapOptionsToLevel:f.mapOptionsToLevel,parentColor:b,parentColorIndex:c,series:f,siblings:e});if(b=f.points[a.i])b.color=n.color,b.colorIndex=n.colorIndex;(a.children||[]).forEach(function(b,c){f.setColorRecursive(b,n.color,
n.colorIndex,c,a.children.length)})}};b.prototype.setPointValues=function(){var a=this,b=a.xAxis,c=a.yAxis,g=a.chart.styledMode;a.points.forEach(function(f){var e=f.node,d=e.pointValues;e=e.visible;if(d&&e){e=d.height;var n=d.width,k=d.x,l=d.y,h=g?0:(a.pointAttribs(f)["stroke-width"]||0)%2/2;d=Math.round(b.toPixels(k,!0))-h;n=Math.round(b.toPixels(k+n,!0))-h;k=Math.round(c.toPixels(l,!0))-h;e=Math.round(c.toPixels(l+e,!0))-h;e={x:Math.min(d,n),y:Math.min(k,e),width:Math.abs(n-d),height:Math.abs(e-
k)};f.plotX=e.x+e.width/2;f.plotY=e.y+e.height/2;f.shapeArgs=e}else delete f.plotX,delete f.plotY})};b.prototype.setRootNode=function(a,b,c){a=I({newRootId:a,previousRootId:this.rootNode,redraw:D(b,!0),series:this},c);M(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})};b.prototype.setState=function(a){this.options.inactiveOtherPoints=!0;g.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=
!1};b.prototype.setTreeValues=function(a){var b=this,f=b.options,c=b.nodeMap[b.rootNode];f=e.isBoolean(f.levelIsConstant)?f.levelIsConstant:!0;var g=0,d=[],n=b.points[a.i];a.children.forEach(function(a){a=b.setTreeValues(a);d.push(a);a.ignore||(g+=a.val)});S(d,function(a,b){return(a.sortIndex||0)-(b.sortIndex||0)});var k=D(n&&n.options.value,g);n&&(n.value=k);I(a,{children:d,childrenTotal:g,ignore:!(D(n&&n.visible,!0)&&0<k),isLeaf:a.visible&&!g,levelDynamic:a.level-(f?0:c.level),name:D(n&&n.name,
""),sortIndex:D(n&&n.sortIndex,-k),val:k});return a};b.prototype.sliceAndDice=function(a,b){return this.algorithmFill(!0,a,b)};b.prototype.squarified=function(a,b){return this.algorithmLowAspectRatio(!0,a,b)};b.prototype.strip=function(a,b){return this.algorithmLowAspectRatio(!1,a,b)};b.prototype.stripes=function(a,b){return this.algorithmFill(!1,a,b)};b.prototype.translate=function(){var a=this,b=a.options,c=F(a);g.prototype.translate.call(a);var d=a.tree=a.getTree();var n=a.nodeMap[c];""===c||n&&
n.children.length||(a.setRootNode("",!1),c=a.rootNode,n=a.nodeMap[c]);a.mapOptionsToLevel=K({from:n.level+1,levels:b.levels,to:d.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});e.recursive(a.nodeMap[a.rootNode],function(b){var c=!1,f=b.parent;b.visible=!0;if(f||""===f)c=a.nodeMap[f];return c});e.recursive(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(d);
a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=c={x:0,y:0,width:e.AXIS_MAX,height:e.AXIS_MAX};a.nodeMap[""].values=c=A(c,{width:c.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:d.val});a.calculateChildrenAreas(d,c);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=n.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()};b.defaultOptions=
A(z.defaultOptions,{allowTraversingTree:!1,animationLimit:250,borderRadius:0,showInLegend:!1,marker:void 0,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return n(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,traverseUpButton:{position:{align:"right",
x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",brightness:v?0:.1,halo:!1,opacity:.75,shadow:!1}}});return b}(z);I(u.prototype,{buildKDTree:a,colorKey:"colorValue",directTouch:!0,drawLegendSymbol:t.drawRectangle,getExtremesFromAll:!0,getSymbol:a,optionalAxis:"colorAxis",parallelArrays:["x","y","value","colorValue"],pointArrayMap:["value"],pointClass:k,trackerGroups:["group","dataLabelsGroup"],utils:{recursive:e.recursive}});p.registerSeriesType("treemap",
u);"";return u});v(a,"Series/Sunburst/SunburstPoint.js",[a["Series/DrawPointComposition.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,h,d){var t=this&&this.__extends||function(){var a=function(e,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(e,d)};return function(e,d){function c(){this.constructor=e}a(e,d);e.prototype=null===d?Object.create(d):(c.prototype=
d.prototype,new c)}}(),p=h.series.prototype.pointClass,q=d.correctFloat;d=d.extend;h=function(a){function e(){var e=null!==a&&a.apply(this,arguments)||this;e.node=void 0;e.options=void 0;e.series=void 0;e.shapeExisting=void 0;return e}t(e,a);e.prototype.getDataLabelPath=function(a){var c=this.series.chart.renderer,b=this.shapeExisting,e=b.start,d=b.end,g=e+(d-e)/2;g=0>g&&g>-Math.PI||g>Math.PI;var k=b.r+(a.options.distance||0);e===-Math.PI/2&&q(d)===q(1.5*Math.PI)&&(e=-Math.PI+Math.PI/360,d=-Math.PI/
360,g=!0);if(d-e>Math.PI){g=!1;var h=!0}this.dataLabelPath&&(this.dataLabelPath=this.dataLabelPath.destroy());this.dataLabelPath=c.arc({open:!0,longArc:h?1:0}).add(a);this.dataLabelPath.attr({start:g?e:d,end:g?d:e,clockwise:+g,x:b.x,y:b.y,r:(k+b.innerR)/2});return this.dataLabelPath};e.prototype.isValid=function(){return!0};return e}(h.seriesTypes.treemap.prototype.pointClass);d(h.prototype,{getClassName:p.prototype.getClassName,haloPath:p.prototype.haloPath,setState:p.prototype.setState});a.compose(h);
return h});v(a,"Series/Sunburst/SunburstUtilities.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,h){var d=a.seriesTypes.treemap,t=h.isNumber,p=h.isObject,q=h.merge,k;(function(a){function e(a,b){var c=[];if(t(a)&&t(b)&&a<=b)for(;a<=b;a++)c.push(a);return c}a.recursive=d.prototype.utils.recursive;a.calculateLevelSizes=function(a,b){b=p(b)?b:{};var c=0,d;if(p(a)){var g=q({},a);a=t(b.from)?b.from:0;var k=t(b.to)?b.to:0;var h=e(a,k);a=Object.keys(g).filter(function(a){return-1===
h.indexOf(+a)});var u=d=t(b.diffRadius)?b.diffRadius:0;h.forEach(function(a){a=g[a];var b=a.levelSize.unit,e=a.levelSize.value;"weight"===b?c+=e:"percentage"===b?(a.levelSize={unit:"pixels",value:e/100*u},d-=a.levelSize.value):"pixels"===b&&(d-=e)});h.forEach(function(a){var b=g[a];"weight"===b.levelSize.unit&&(b=b.levelSize.value,g[a].levelSize={unit:"pixels",value:b/c*d})});a.forEach(function(a){g[a].levelSize={value:0,unit:"pixels"}})}return g};a.getLevelFromAndTo=function(a){var b=a.level;return{from:0<
b?b:1,to:b+a.height}};a.range=e})(k||(k={}));return k});v(a,"Series/Sunburst/SunburstSeries.js",[a["Series/CenteredUtilities.js"],a["Core/Globals.js"],a["Core/Series/SeriesRegistry.js"],a["Series/Sunburst/SunburstPoint.js"],a["Series/Sunburst/SunburstUtilities.js"],a["Series/TreeUtilities.js"],a["Core/Utilities.js"]],function(a,h,d,t,p,q,k){function e(a,b){var c=b.mapIdToNode[a.parent],e=b.series,d=e.chart,g=e.points[a.i];c=C(a,{colors:e.options.colors||d&&d.options.colors,colorIndex:e.colorIndex,
index:b.index,mapOptionsToLevel:b.mapOptionsToLevel,parentColor:c&&c.color,parentColorIndex:c&&c.colorIndex,series:b.series,siblings:b.siblings});a.color=c.color;a.colorIndex=c.colorIndex;g&&(g.color=a.color,g.colorIndex=a.colorIndex,a.sliced=a.id!==b.idRoot?g.sliced:!1);return a}var u=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return a(b,
c)};return function(b,c){function e(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(e.prototype=c.prototype,new e)}}(),c=a.getCenter,b=a.getStartAndEndRadians;a=h.noop;var v=d.series,m=d.seriesTypes;h=m.column;var g=m.treemap,C=q.getColor,F=q.getLevelOptions,z=q.setTreeValues,J=q.updateRootId,K=k.error,L=k.extend,w=k.isNumber,G=k.isObject,E=k.isString,H=k.merge,I=k.splat,M=180/Math.PI;q=function(a){function d(){var b=null!==a&&a.apply(this,arguments)||this;b.center=void 0;b.data=
void 0;b.mapOptionsToLevel=void 0;b.nodeMap=void 0;b.options=void 0;b.points=void 0;b.shapeRoot=void 0;b.startAndEndRadians=void 0;b.tree=void 0;return b}u(d,a);d.prototype.alignDataLabel=function(b,c,d){if(!d.textPath||!d.textPath.enabled)return a.prototype.alignDataLabel.apply(this,arguments)};d.prototype.animate=function(a){var b=this.chart,c=[b.plotWidth/2,b.plotHeight/2],d=b.plotLeft,e=b.plotTop;b=this.group;a?(a={translateX:c[0]+d,translateY:c[1]+e,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},
b.attr(a)):(a={translateX:d,translateY:e,scaleX:1,scaleY:1,rotation:0,opacity:1},b.animate(a,this.options.animation))};d.prototype.drawPoints=function(){var a=this,b=a.mapOptionsToLevel,c=a.shapeRoot,d=a.group,e=a.hasRendered,g=a.rootNode,f=a.idPreviousRoot,k=a.nodeMap,h=k[f],m=h&&h.shapeArgs;h=a.points;var p=a.startAndEndRadians,t=a.chart,q=t&&t.options&&t.options.chart||{},u="boolean"===typeof q.animation?q.animation:!0,z=a.center[3]/2,C=a.chart.renderer,B=!1,E=!1;if(q=!!(u&&e&&g!==f&&a.dataLabelsGroup)){a.dataLabelsGroup.attr({opacity:0});
var F=function(){B=!0;a.dataLabelsGroup&&a.dataLabelsGroup.animate({opacity:1,visibility:"visible"})}}h.forEach(function(h){var n=h.node,l=b[n.level];var q=h.shapeExisting||{};var r=n.shapeArgs||{},A=!(!n.visible||!n.shapeArgs);if(e&&u){var x={};var D={end:r.end,start:r.start,innerR:r.innerR,r:r.r,x:r.x,y:r.y};A?!h.graphic&&m&&(x=g===h.id?{start:p.start,end:p.end}:m.end<=r.start?{start:p.end,end:p.end}:{start:p.start,end:p.start},x.innerR=x.r=z):h.graphic&&(f===h.id?D={innerR:z,r:z}:c&&(D=c.end<=
q.start?{innerR:z,r:z,start:p.end,end:p.end}:{innerR:z,r:z,start:p.start,end:p.start}));q=x}else D=r,q={};x=[r.plotX,r.plotY];if(!h.node.isLeaf)if(g===h.id){var y=k[g];y=y.parent}else y=h.id;L(h,{shapeExisting:r,tooltipPos:x,drillId:y,name:""+(h.name||h.id||h.index),plotX:r.plotX,plotY:r.plotY,value:n.val,isInside:A,isNull:!A});y=h.options;n=G(r)?r:{};y=G(y)?y.dataLabels:{};l=I(G(l)?l.dataLabels:{})[0];l=H({style:{}},l,y);y=l.rotationMode;if(!w(l.rotation)){if("auto"===y||"circular"===y)if(1>h.innerArcLength&&
h.outerArcLength>n.radius){var v=0;h.dataLabelPath&&"circular"===y&&(l.textPath={enabled:!0})}else 1<h.innerArcLength&&h.outerArcLength>1.5*n.radius?"circular"===y?l.textPath={enabled:!0,attributes:{dy:5}}:y="parallel":(h.dataLabel&&h.dataLabel.textPathWrapper&&"circular"===y&&(l.textPath={enabled:!1}),y="perpendicular");"auto"!==y&&"circular"!==y&&(v=n.end-(n.end-n.start)/2);l.style.width="parallel"===y?Math.min(2.5*n.radius,(h.outerArcLength+h.innerArcLength)/2):n.radius;"perpendicular"===y&&h.series.chart.renderer.fontMetrics(l.style.fontSize).h>
h.outerArcLength&&(l.style.width=1);l.style.width=Math.max(l.style.width-2*(l.padding||0),1);v=v*M%180;"parallel"===y&&(v-=90);90<v?v-=180:-90>v&&(v+=180);l.rotation=v}l.textPath&&(0===h.shapeExisting.innerR&&l.textPath.enabled?(l.rotation=0,l.textPath.enabled=!1,l.style.width=Math.max(2*h.shapeExisting.r-2*(l.padding||0),1)):h.dlOptions&&h.dlOptions.textPath&&!h.dlOptions.textPath.enabled&&"circular"===y&&(l.textPath.enabled=!0),l.textPath.enabled&&(l.rotation=0,l.style.width=Math.max((h.outerArcLength+
h.innerArcLength)/2-2*(l.padding||0),1)));0===l.rotation&&(l.rotation=.001);h.dlOptions=l;if(!E&&A){E=!0;var Q=F}h.draw({animatableAttribs:D,attribs:L(q,!t.styledMode&&a.pointAttribs(h,h.selected&&"select")),onComplete:Q,group:d,renderer:C,shapeType:"arc",shapeArgs:r})});q&&E?(a.hasRendered=!1,a.options.dataLabels.defer=!0,v.prototype.drawDataLabels.call(a),a.hasRendered=!0,B&&F()):v.prototype.drawDataLabels.call(a)};d.prototype.layoutAlgorithm=function(a,b,c){var d=a.start,e=a.end-d,g=a.val,f=a.x,
h=a.y,k=c&&G(c.levelSize)&&w(c.levelSize.value)?c.levelSize.value:0,n=a.r,m=n+k,p=c&&w(c.slicedOffset)?c.slicedOffset:0;return(b||[]).reduce(function(a,b){var c=1/g*b.val*e,l=d+c/2,r=f+Math.cos(l)*p;l=h+Math.sin(l)*p;b={x:b.sliced?r:f,y:b.sliced?l:h,innerR:n,r:m,radius:k,start:d,end:d+c};a.push(b);d=b.end;return a},[])};d.prototype.setShapeArgs=function(a,b,c){var d=[],e=c[a.level+1];a=a.children.filter(function(a){return a.visible});d=this.layoutAlgorithm(b,a,e);a.forEach(function(a,b){b=d[b];var e=
b.start+(b.end-b.start)/2,f=b.innerR+(b.r-b.innerR)/2,g=b.end-b.start;f=0===b.innerR&&6.28<g?{x:b.x,y:b.y}:{x:b.x+Math.cos(e)*f,y:b.y+Math.sin(e)*f};var h=a.val?a.childrenTotal>a.val?a.childrenTotal:a.val:a.childrenTotal;this.points[a.i]&&(this.points[a.i].innerArcLength=g*b.innerR,this.points[a.i].outerArcLength=g*b.r);a.shapeArgs=H(b,{plotX:f.x,plotY:f.y+4*Math.abs(Math.cos(e))});a.values=H(b,{val:h});a.children.length&&this.setShapeArgs(a,a.values,c)},this)};d.prototype.translate=function(){var a=
this,d=a.options,g=a.center=c.call(a),h=a.startAndEndRadians=b(d.startAngle,d.endAngle),k=g[3]/2,m=g[2]/2-k,f=J(a),l=a.nodeMap,r=l&&l[f],q={};a.shapeRoot=r&&r.shapeArgs;v.prototype.translate.call(a);var t=a.tree=a.getTree();l=a.nodeMap;r=l[f];var u=E(r.parent)?r.parent:"";u=l[u];var w=p.getLevelFromAndTo(r);var B=w.from,C=w.to;w=F({from:B,levels:a.options.levels,to:C,defaults:{colorByPoint:d.colorByPoint,dataLabels:d.dataLabels,levelIsConstant:d.levelIsConstant,levelSize:d.levelSize,slicedOffset:d.slicedOffset}});
w=p.calculateLevelSizes(w,{diffRadius:m,from:B,to:C});z(t,{before:e,idRoot:f,levelIsConstant:d.levelIsConstant,mapOptionsToLevel:w,mapIdToNode:l,points:a.points,series:a});d=l[""].shapeArgs={end:h.end,r:k,start:h.start,val:r.val,x:g[0],y:g[1]};this.setShapeArgs(u,d,w);a.mapOptionsToLevel=w;a.data.forEach(function(b){q[b.id]&&K(31,!1,a.chart);q[b.id]=!0});q={}};d.defaultOptions=H(g.defaultOptions,{center:["50%","50%"],colorByPoint:!1,opacity:1,dataLabels:{allowOverlap:!0,defer:!0,rotationMode:"auto",
style:{textOverflow:"ellipsis"}},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10});return d}(g);L(q.prototype,{drawDataLabels:a,pointAttribs:h.prototype.pointAttribs,pointClass:t,utils:p});d.registerSeriesType("sunburst",q);"";return q});v(a,"masters/modules/sunburst.src.js",[],function(){})});
//# sourceMappingURL=sunburst.js.map