/*
 Highcharts JS v9.3.2 (2021-12-20)

 (c) 2014-2021 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
'use strict';(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(v){a(v);a.Highcharts=v;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function v(a,h,b,q){a.hasOwnProperty(h)||(a[h]=q.apply(null,b))}a=a?a._modules:{};v(a,"Series/ColorMapMixin.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,h,b){var q=
a.noop;a=a.seriesTypes;var g=b.defined;b=b.addEvent;b(h,"afterSetState",function(a){this.moveToTopOnHover&&this.graphic&&this.graphic.attr({zIndex:a&&"hover"===a.state?1:0})});return{PointMixin:{dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value}},SeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:q,parallelArrays:["x","y","value"],
colorKey:"value",pointAttribs:a.column.prototype.pointAttribs,colorAttribs:function(a){var m={};!g(a.color)||a.state&&"normal"!==a.state||(m[this.colorProp||"fill"]=a.color);return m}}}});v(a,"Series/Treemap/TreemapAlgorithmGroup.js",[],function(){return function(){function a(a,b,q,g){this.height=a;this.width=b;this.plot=g;this.startDirection=this.direction=q;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,b){return Math.max(a/
b,b/a)}}}a.prototype.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,
this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};a.prototype.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0};return a}()});v(a,"Series/DrawPointComposition.js",[],function(){var a;(function(a){function b(a){var b=this,f=a.animatableAttribs,m=a.onComplete,c=a.css,l=a.renderer,K=this.series&&this.series.chart.hasRendered?void 0:this.series&&this.series.options.animation,k=this.graphic;a.attribs=a.attribs||{};a.attribs["class"]=this.getClassName();if(this.shouldDraw())k||
(this.graphic=k=l[a.shapeType](a.shapeArgs).add(a.group)),k.css(c).attr(a.attribs).animate(f,a.isNew?!1:K,m);else if(k){var e=function(){b.graphic=k=k&&k.destroy();"function"===typeof m&&m()};Object.keys(f).length?k.animate(f,void 0,function(){e()}):e()}}function q(){return!this.isNull}var g=[];a.compose=function(a){if(-1===g.indexOf(a)){g.push(a);var m=a.prototype;m.draw=b;m.shouldDraw||(m.shouldDraw=q)}return a}})(a||(a={}));return a});v(a,"Series/Treemap/TreemapPoint.js",[a["Series/DrawPointComposition.js"],
a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,h,b){var q=this&&this.__extends||function(){var a=function(c,b){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,e){a.__proto__=e}||function(a,e){for(var c in e)e.hasOwnProperty(c)&&(a[c]=e[c])};return a(c,b)};return function(c,b){function k(){this.constructor=c}a(c,b);c.prototype=null===b?Object.create(b):(k.prototype=b.prototype,new k)}}(),g=h.series.prototype.pointClass,m=h.seriesTypes;h=m.pie.prototype.pointClass;
var w=b.extend,f=b.isNumber,u=b.pick;b=function(a){function c(){var c=null!==a&&a.apply(this,arguments)||this;c.name=void 0;c.node=void 0;c.options=void 0;c.series=void 0;c.value=void 0;return c}q(c,a);c.prototype.getClassName=function(){var a=g.prototype.getClassName.call(this),c=this.series,e=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||u(e.interactByLeaf,!e.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";
return a};c.prototype.isValid=function(){return!(!this.id&&!f(this.value))};c.prototype.setState=function(a){g.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})};c.prototype.shouldDraw=function(){return f(this.plotY)&&null!==this.y};return c}(m.scatter.prototype.pointClass);w(b.prototype,{setVisible:h.prototype.setVisible});a.compose(b);return b});v(a,"Series/Treemap/TreemapUtilities.js",[a["Core/Utilities.js"]],function(a){var h=a.objectEach,b;(function(a){function b(a,
h,f){void 0===f&&(f=this);a=h.call(f,a);!1!==a&&b(a,h,f)}a.AXIS_MAX=100;a.isBoolean=function(a){return"boolean"===typeof a};a.eachObject=function(a,b,f){f=f||this;h(a,function(h,c){b.call(f,h,c,a)})};a.recursive=b})(b||(b={}));return b});v(a,"Series/TreeUtilities.js",[a["Core/Color/Color.js"],a["Core/Utilities.js"]],function(a,h){function b(a,l){var c=l.before,k=l.idRoot,e=l.mapIdToNode[k],n=l.points[a.i],z=n&&n.options||{},r=[],f=0;a.levelDynamic=a.level-(!1!==l.levelIsConstant?0:e.level);a.name=
u(n&&n.name,"");a.visible=k===a.id||!0===l.visible;"function"===typeof c&&(a=c(a,l));a.children.forEach(function(e,c){var n=q({},l);q(n,{index:c,siblings:a.children.length,visible:a.visible});e=b(e,n);r.push(e);e.visible&&(f+=e.val)});c=u(z.value,f);a.visible=0<=c&&(0<f||a.visible);a.children=r;a.childrenTotal=f;a.isLeaf=a.visible&&!f;a.val=c;return a}var q=h.extend,g=h.isArray,m=h.isNumber,w=h.isObject,f=h.merge,u=h.pick;return{getColor:function(c,b){var f=b.index,k=b.mapOptionsToLevel,e=b.parentColor,
n=b.parentColorIndex,z=b.series,r=b.colors,l=b.siblings,h=z.points,g=z.chart.options.chart,x;if(c){h=h[c.i];c=k[c.level]||{};if(k=h&&c.colorByPoint){var m=h.index%(r?r.length:g.colorCount);var q=r&&r[m]}if(!z.chart.styledMode){r=h&&h.options.color;g=c&&c.color;if(x=e)x=(x=c&&c.colorVariation)&&"brightness"===x.key&&f&&l?a.parse(e).brighten(f/l*x.to).get():e;x=u(r,g,q,x,z.color)}var w=u(h&&h.options.colorIndex,c&&c.colorIndex,m,n,b.colorIndex)}return{color:x,colorIndex:w}},getLevelOptions:function(a){var c=
null;if(w(a)){c={};var b=m(a.from)?a.from:1;var k=a.levels;var e={};var n=w(a.defaults)?a.defaults:{};g(k)&&(e=k.reduce(function(a,e){if(w(e)&&m(e.level)){var c=f({},e);var k=u(c.levelIsConstant,n.levelIsConstant);delete c.levelIsConstant;delete c.level;e=e.level+(k?0:b-1);w(a[e])?f(!0,a[e],c):a[e]=c}return a},{}));k=m(a.to)?a.to:1;for(a=0;a<=k;a++)c[a]=f({},n,w(e[a])?e[a]:{})}return c},setTreeValues:b,updateRootId:function(a){if(w(a)){var c=w(a.options)?a.options:{};c=u(a.rootNode,c.rootId,"");w(a.userOptions)&&
(a.userOptions.rootId=c);a.rootNode=c}return c}}});v(a,"Extensions/Breadcrumbs.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/DefaultOptions.js"],a["Core/Utilities.js"],a["Core/FormatUtilities.js"]],function(a,h,b,q,g){var m=g.format;g=q.addEvent;var w=q.objectEach,f=q.extend,u=q.fireEvent,c=q.merge,l=q.pick,v=q.defined;f(b.defaultOptions.lang,{mainBreadcrumb:"Main"});b=function(){function a(e,n){this.group=void 0;this.list=[];this.elementList={};this.isDirty=!0;this.level=0;this.options=
void 0;n=c(e.options.drilldown&&e.options.drilldown.drillUpButton,a.defaultBreadcrumbsOptions,n);this.chart=e;this.options=n||{}}a.prototype.updateProperties=function(a){this.setList(a);this.setLevel();this.isDirty=!0};a.prototype.setList=function(a){this.list=a};a.prototype.setLevel=function(){this.level=this.list.length&&this.list.length-1};a.prototype.getLevel=function(){return this.level};a.prototype.getButtonText=function(a){var e=this.chart,c=this.options,b=e.options.lang,f=l(c.format,c.showFullPath?
"{level.name}":"\u2190 {level.name}");b=b&&l(b.drillUpText,b.mainBreadcrumb);a=c.formatter&&c.formatter(a)||m(f,{level:a.levelOptions},e)||"";"\u2190 "===a&&v(b)&&(a=c.showFullPath?b:"\u2190 "+b);return a};a.prototype.redraw=function(){this.isDirty&&this.render();this.group&&this.group.align();this.isDirty=!1};a.prototype.render=function(){var a=this.chart,c=this.options;!this.group&&c&&(this.group=a.renderer.g("breadcrumbs-group").addClass("highcharts-no-tooltip highcharts-breadcrumbs").attr({zIndex:c.zIndex}).add());
c.showFullPath?this.renderFullPathButtons():this.renderSingleButton();this.alignBreadcrumbsGroup()};a.prototype.renderFullPathButtons=function(){this.destroySingleButton();this.resetElementListState();this.updateListElements();this.destroyListElements()};a.prototype.renderSingleButton=function(){var a=this.chart,c=this.list,b=this.options.buttonSpacing;this.destroyListElements();var r=this.group?this.group.getBBox().width:b;c=c[c.length-2];!a.drillUpButton&&0<this.level?a.drillUpButton=this.renderButton(c,
r,b):a.drillUpButton&&(0<this.level?this.updateSingleButton():this.destroySingleButton())};a.prototype.alignBreadcrumbsGroup=function(a){if(this.group){var e=this.options,b=e.buttonTheme,r=e.position,f="chart"===e.relativeTo||"spacingBox"===e.relativeTo?void 0:"scrollablePlotBox",h=this.group.getBBox();e=2*(b.padding||0)+e.buttonSpacing;r.width=h.width+e;r.height=h.height+e;r=c(r);a&&(r.x+=a);r.y=l(r.y,this.yOffset,0);this.group.align(r,!0,f)}};a.prototype.renderButton=function(a,b,f){var e=this,
h=this.chart,n=e.options,k=c(n.buttonTheme),g=k.states;delete k.states;b=h.renderer.button(e.getButtonText(a),b,f,function(c){var b=n.events&&n.events.click,f;b&&(f=b.call(e,c,a));!1!==f&&(c.newLevel=n.showFullPath?a.level:e.level-1,u(e,"up",c))},k,g&&g.hover,g&&g.select,g&&g.disabled).addClass("highcharts-breadcrumbs-button").add(e.group);h.styledMode||b.attr(n.style);return b};a.prototype.renderSeparator=function(a,c){var e=this.chart,b=this.options.separator;a=e.renderer.label(b.text,a,c,void 0,
void 0,void 0,!1).addClass("highcharts-breadcrumbs-separator").add(this.group);e.styledMode||a.css(b.style);return a};a.prototype.update=function(a){c(!0,this.options,a);this.destroy();this.isDirty=!0};a.prototype.updateSingleButton=function(){var a=this.chart,c=this.list[this.level-1];a.drillUpButton&&a.drillUpButton.attr({text:this.getButtonText(c)})};a.prototype.destroy=function(){this.destroySingleButton();this.destroyListElements(!0);this.group&&this.group.destroy();this.group=void 0};a.prototype.destroyListElements=
function(a){var c=this.elementList;w(c,function(b,e){if(a||!c[e].updated)b=c[e],b.button&&b.button.destroy(),b.separator&&b.separator.destroy(),delete b.button,delete b.separator,delete c[e]});a&&(this.elementList={})};a.prototype.destroySingleButton=function(){this.chart.drillUpButton&&(this.chart.drillUpButton.destroy(),this.chart.drillUpButton=void 0)};a.prototype.resetElementListState=function(){w(this.elementList,function(a){a.updated=!1})};a.prototype.updateListElements=function(){var a=function(a,
c){return a.getBBox().width+c},c=this,b=c.elementList,f=c.options.buttonSpacing,h=c.list,k=c.group?a(c.group,f):f,g;h.forEach(function(e,n){n=n===h.length-1;if(b[e.level]){g=b[e.level];var l=g.button;g.separator||n?g.separator&&n&&(g.separator.destroy(),delete g.separator):(k+=f,g.separator=c.renderSeparator(k,f),k+=a(g.separator,f));b[e.level].updated=!0}else{l=c.renderButton(e,k,f);k+=a(l,f);if(!n){var m=c.renderSeparator(k,f);k+=a(m,f)}b[e.level]={button:l,separator:m,updated:!0}}l&&l.setState(n?
2:0)})};a.defaultBreadcrumbsOptions={buttonTheme:{fill:"none",height:18,padding:2,"stroke-width":0,zIndex:7,states:{select:{fill:"none"}},style:{color:"#335cad"}},buttonSpacing:5,floating:!1,format:void 0,relativeTo:"plotBox",position:{align:"left",verticalAlign:"top",x:0,y:void 0},separator:{text:"/",style:{color:"#666666"}},showFullPath:!0,style:{},useHTML:!1,zIndex:7};return a}();h.Breadcrumbs||(h.Breadcrumbs=b,g(a,"getMargins",function(){var a=this.breadcrumbs;if(a&&!a.options.floating&&a.level){var c=
a.options,b=c.buttonTheme;b=(b.height||0)+2*(b.padding||0)+c.buttonSpacing;c=c.position.verticalAlign;"bottom"===c?(this.marginBottom=(this.marginBottom||0)+b,a.yOffset=b):"middle"!==c?(this.plotTop+=b,a.yOffset=-b):a.yOffset=void 0}}),g(a,"redraw",function(){this.breadcrumbs&&this.breadcrumbs.redraw()}),g(a,"destroy",function(){this.breadcrumbs&&(this.breadcrumbs.destroy(),this.breadcrumbs=void 0)}),g(a,"afterShowResetZoom",function(){if(this.breadcrumbs){var a=this.resetZoomButton&&this.resetZoomButton.getBBox(),
c=this.breadcrumbs.options;a&&"right"===c.position.align&&"plotBox"===c.relativeTo&&this.breadcrumbs.alignBreadcrumbsGroup(-a.width-c.buttonSpacing)}}),g(a,"selection",function(a){!0===a.resetSelection&&this.breadcrumbs&&this.breadcrumbs.alignBreadcrumbsGroup()}));"";return b});v(a,"Series/Treemap/TreemapComposition.js",[a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapUtilities.js"],a["Core/Utilities.js"]],function(a,h,b){var q=b.addEvent,g=b.extend,m=!1;q(a.series,"afterBindAxes",function(){var a=
this.xAxis,b=this.yAxis;if(a&&b)if(this.is("treemap")){var q={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,minPadding:0,max:h.AXIS_MAX,maxPadding:0,startOnTick:!1,title:void 0,tickPositions:[]};g(b.options,q);g(a.options,q);m=!0}else m&&(b.setOptions(b.userOptions),a.setOptions(a.userOptions),m=!1)})});v(a,"Series/Treemap/TreemapSeries.js",[a["Core/Color/Color.js"],a["Series/ColorMapMixin.js"],a["Core/Globals.js"],a["Core/Legend/LegendSymbol.js"],a["Core/Series/SeriesRegistry.js"],a["Series/Treemap/TreemapAlgorithmGroup.js"],
a["Series/Treemap/TreemapPoint.js"],a["Series/Treemap/TreemapUtilities.js"],a["Series/TreeUtilities.js"],a["Extensions/Breadcrumbs.js"],a["Core/Utilities.js"]],function(a,h,b,q,g,m,w,f,u,c,l){var v=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var p in d)d.hasOwnProperty(p)&&(a[p]=d[p])};return a(c,d)};return function(c,d){function p(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):
(p.prototype=d.prototype,new p)}}(),k=a.parse;a=b.noop;var e=g.series;b=g.seriesTypes;var n=b.column,z=b.heatmap,r=b.scatter,J=u.getColor,L=u.getLevelOptions,M=u.updateRootId,x=l.addEvent,N=l.correctFloat,B=l.defined,O=l.error,D=l.extend,P=l.fireEvent,H=l.isArray,Q=l.isObject,G=l.isString,A=l.merge,y=l.pick,R=l.stableSort;u=function(a){function b(){var d=null!==a&&a.apply(this,arguments)||this;d.axisRatio=void 0;d.data=void 0;d.mapOptionsToLevel=void 0;d.nodeMap=void 0;d.options=void 0;d.points=void 0;
d.rootNode=void 0;d.tree=void 0;d.level=void 0;return d}v(b,a);b.prototype.algorithmCalcPoints=function(a,b,c,e){var d,p,t,f,F=c.lW,h=c.lH,g=c.plot,k=0,l=c.elArr.length-1;if(b)F=c.nW,h=c.nH;else var m=c.elArr[c.elArr.length-1];c.elArr.forEach(function(a){if(b||k<l)0===c.direction?(d=g.x,p=g.y,t=F,f=a/t):(d=g.x,p=g.y,f=h,t=a/f),e.push({x:d,y:p,width:t,height:N(f)}),0===c.direction?g.y+=f:g.x+=t;k+=1});c.reset();0===c.direction?c.width-=F:c.height-=h;g.y=g.parent.y+(g.parent.height-c.height);g.x=g.parent.x+
(g.parent.width-c.width);a&&(c.direction=1-c.direction);b||c.addElement(m)};b.prototype.algorithmFill=function(a,b,c){var d=[],p,t=b.direction,e=b.x,f=b.y,g=b.width,h=b.height,k,l,m,n;c.forEach(function(c){p=c.val/b.val*b.height*b.width;k=e;l=f;0===t?(n=h,m=p/n,g-=m,e+=m):(m=g,n=p/m,h-=n,f+=n);d.push({x:k,y:l,width:m,height:n});a&&(t=1-t)});return d};b.prototype.algorithmLowAspectRatio=function(a,b,c){var d=[],p=this,t,e={x:b.x,y:b.y,parent:b},f=0,g=c.length-1,h=new m(b.height,b.width,b.direction,
e);c.forEach(function(c){t=c.val/b.val*b.height*b.width;h.addElement(t);h.lP.nR>h.lP.lR&&p.algorithmCalcPoints(a,!1,h,d,e);f===g&&p.algorithmCalcPoints(a,!0,h,d,e);f+=1});return d};b.prototype.alignDataLabel=function(a,b,c){var d=c.style;d&&!B(d.textOverflow)&&b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:d.width+="px"});n.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})};b.prototype.buildNode=function(a,
b,c,e,E){var d=this,p=[],t=d.points[b],f=0,g;(e[a]||[]).forEach(function(b){g=d.buildNode(d.points[b].id,b,c+1,e,a);f=Math.max(g.height+1,f);p.push(g)});b={id:a,i:b,children:p,height:f,level:c,parent:E,visible:!1};d.nodeMap[b.id]=b;t&&(t.node=b);return b};b.prototype.calculateChildrenAreas=function(a,b){var d=this,c=d.options,p=d.mapOptionsToLevel[a.level+1],e=y(d[p&&p.layoutAlgorithm]&&p.layoutAlgorithm,c.layoutAlgorithm),g=c.alternateStartingDirection,h=[];a=a.children.filter(function(a){return!a.ignore});
p&&p.layoutStartingDirection&&(b.direction="vertical"===p.layoutStartingDirection?0:1);h=d[e](b,a);a.forEach(function(a,c){c=h[c];a.values=A(c,{val:a.childrenTotal,direction:g?1-b.direction:b.direction});a.pointValues=A(c,{x:c.x/d.axisRatio,y:f.AXIS_MAX-c.y-c.height,width:c.width/d.axisRatio});a.children.length&&d.calculateChildrenAreas(a,a.values)})};b.prototype.createList=function(a){var d=this.chart,b=[];if(d.breadcrumbs){var c=0;b.push({level:c,levelOptions:d.series[0]});d=a.target.nodeMap[a.newRootId];
for(var e=[];d.parent||""===d.parent;)e.push(d),d=a.target.nodeMap[d.parent];e.reverse().forEach(function(a){b.push({level:++c,levelOptions:a})});1>=b.length&&(b.length=0)}return b};b.prototype.drawDataLabels=function(){var a=this,b=a.mapOptionsToLevel,c,f;a.points.filter(function(a){return a.node.visible}).forEach(function(d){f=b[d.node.level];c={style:{}};d.node.isLeaf||(c.enabled=!1);f&&f.dataLabels&&(c=A(c,f.dataLabels),a._hasPointLabels=!0);d.shapeArgs&&(c.style.width=d.shapeArgs.width,d.dataLabel&&
d.dataLabel.css({width:d.shapeArgs.width+"px"}));d.dlOptions=A(c,d.options.dataLabels)});e.prototype.drawDataLabels.call(this)};b.prototype.drawPoints=function(){var a=this,b=a.chart,c=b.renderer,e=b.styledMode,f=a.options,g=e?{}:f.shadow,h=f.borderRadius,k=b.pointCount<f.animationLimit,l=f.allowTraversingTree;a.points.forEach(function(b){var d=b.node.levelDynamic,p={},t={},I={},C="level-group-"+b.node.level,E=!!b.graphic,m=k&&E,n=b.shapeArgs;b.shouldDraw()&&(b.isInside=!0,h&&(t.r=h),A(!0,m?p:t,E?
n:{},e?{}:a.pointAttribs(b,b.selected?"select":void 0)),a.colorAttribs&&e&&D(I,a.colorAttribs(b)),a[C]||(a[C]=c.g(C).attr({zIndex:1E3-(d||0)}).add(a.group),a[C].survive=!0));b.draw({animatableAttribs:p,attribs:t,css:I,group:a[C],renderer:c,shadow:g,shapeArgs:n,shapeType:"rect"});l&&b.graphic&&(b.drillId=f.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})};b.prototype.drillToByGroup=function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b};b.prototype.drillToByLeaf=
function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b};b.prototype.drillToNode=function(a,b){O(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,b)};b.prototype.drillUp=function(){var a=this.nodeMap[this.rootNode];a&&G(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})};b.prototype.getExtremes=function(){var a=e.prototype.getExtremes.call(this,this.colorValueData),
b=a.dataMax;this.valueMin=a.dataMin;this.valueMax=b;return e.prototype.getExtremes.call(this)};b.prototype.getListOfParents=function(a,b){a=H(a)?a:[];var c=H(b)?b:[];b=a.reduce(function(a,b,c){b=y(b.parent,"");"undefined"===typeof a[b]&&(a[b]=[]);a[b].push(c);return a},{"":[]});f.eachObject(b,function(a,b,d){""!==b&&-1===c.indexOf(b)&&(a.forEach(function(a){d[""].push(a)}),delete d[b])});return b};b.prototype.getTree=function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,
a);this.nodeMap={};return this.buildNode("",-1,0,a)};b.prototype.hasData=function(){return!!this.processedXData.length};b.prototype.init=function(a,b){var d=this,f=A(b.drillUpButton,b.breadcrumbs);this.colorAttribs=h.SeriesMixin.colorAttribs;var p=x(d,"setOptions",function(a){a=a.userOptions;B(a.allowDrillToNode)&&!B(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);B(a.drillUpButton)&&!B(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});
e.prototype.init.call(d,a,b);delete d.opacity;d.eventsToUnbind.push(p);d.options.allowTraversingTree&&(d.eventsToUnbind.push(x(d,"click",d.onClickDrillToNode)),d.eventsToUnbind.push(x(d,"setRootNode",function(a){var b=d.chart;b.breadcrumbs&&b.breadcrumbs.updateProperties(d.createList(a))})),d.eventsToUnbind.push(x(d,"update",function(a,b){(b=this.chart.breadcrumbs)&&a.options.breadcrumbs&&b.update(a.options.breadcrumbs)})),d.eventsToUnbind.push(x(d,"destroy",function(a){var b=this.chart;b.breadcrumbs&&
(b.breadcrumbs.destroy(),a.keepEventsForUpdate||(b.breadcrumbs=void 0))})));a.breadcrumbs||(a.breadcrumbs=new c(a,f));d.eventsToUnbind.push(x(a.breadcrumbs,"up",function(a){a=this.level-a.newLevel;for(var b=0;b<a;b++)d.drillUp()}))};b.prototype.onClickDrillToNode=function(a){var b=(a=a.point)&&a.drillId;G(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))};b.prototype.pointAttribs=function(a,b){var c=Q(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{};c=this.options;
var e=b&&c.states[b]||{},f=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||d.borderColor||e.borderColor||c.borderColor,"stroke-width":y(a&&a.borderWidth,d.borderWidth,e.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||e.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==f.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==f.indexOf("highcharts-internal-node-interactive")?(b=y(e.opacity,c.opacity),a.fill=k(a.fill).setOpacity(b).get(),
a.cursor="pointer"):-1!==f.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=k(a.fill).brighten(e.brightness).get());return a};b.prototype.setColorRecursive=function(a,b,c,e,f){var d=this,g=d&&d.chart;g=g&&g.options&&g.options.colors;if(a){var h=J(a,{colors:g,index:e,mapOptionsToLevel:d.mapOptionsToLevel,parentColor:b,parentColorIndex:c,series:d,siblings:f});if(b=d.points[a.i])b.color=h.color,b.colorIndex=h.colorIndex;(a.children||[]).forEach(function(b,c){d.setColorRecursive(b,h.color,
h.colorIndex,c,a.children.length)})}};b.prototype.setPointValues=function(){var a=this,b=a.xAxis,c=a.yAxis,e=a.chart.styledMode;a.points.forEach(function(d){var f=d.node,g=f.pointValues;f=f.visible;if(g&&f){f=g.height;var h=g.width,p=g.x,k=g.y,l=e?0:(a.pointAttribs(d)["stroke-width"]||0)%2/2;g=Math.round(b.toPixels(p,!0))-l;h=Math.round(b.toPixels(p+h,!0))-l;p=Math.round(c.toPixels(k,!0))-l;f=Math.round(c.toPixels(k+f,!0))-l;f={x:Math.min(g,h),y:Math.min(p,f),width:Math.abs(h-g),height:Math.abs(f-
p)};d.plotX=f.x+f.width/2;d.plotY=f.y+f.height/2;d.shapeArgs=f}else delete d.plotX,delete d.plotY})};b.prototype.setRootNode=function(a,b,c){a=D({newRootId:a,previousRootId:this.rootNode,redraw:y(b,!0),series:this},c);P(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})};b.prototype.setState=function(a){this.options.inactiveOtherPoints=!0;e.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=
!1};b.prototype.setTreeValues=function(a){var b=this,c=b.options,d=b.nodeMap[b.rootNode];c=f.isBoolean(c.levelIsConstant)?c.levelIsConstant:!0;var e=0,g=[],h=b.points[a.i];a.children.forEach(function(a){a=b.setTreeValues(a);g.push(a);a.ignore||(e+=a.val)});R(g,function(a,b){return(a.sortIndex||0)-(b.sortIndex||0)});var k=y(h&&h.options.value,e);h&&(h.value=k);D(a,{children:g,childrenTotal:e,ignore:!(y(h&&h.visible,!0)&&0<k),isLeaf:a.visible&&!e,levelDynamic:a.level-(c?0:d.level),name:y(h&&h.name,
""),sortIndex:y(h&&h.sortIndex,-k),val:k});return a};b.prototype.sliceAndDice=function(a,b){return this.algorithmFill(!0,a,b)};b.prototype.squarified=function(a,b){return this.algorithmLowAspectRatio(!0,a,b)};b.prototype.strip=function(a,b){return this.algorithmLowAspectRatio(!1,a,b)};b.prototype.stripes=function(a,b){return this.algorithmFill(!1,a,b)};b.prototype.translate=function(){var a=this,b=a.options,c=M(a);e.prototype.translate.call(a);var g=a.tree=a.getTree();var h=a.nodeMap[c];""===c||h&&
h.children.length||(a.setRootNode("",!1),c=a.rootNode,h=a.nodeMap[c]);a.mapOptionsToLevel=L({from:h.level+1,levels:b.levels,to:g.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});f.recursive(a.nodeMap[a.rootNode],function(b){var c=!1,d=b.parent;b.visible=!0;if(d||""===d)c=a.nodeMap[d];return c});f.recursive(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(g);
a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=c={x:0,y:0,width:f.AXIS_MAX,height:f.AXIS_MAX};a.nodeMap[""].values=c=A(c,{width:c.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:g.val});a.calculateChildrenAreas(g,c);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=h.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()};b.defaultOptions=
A(r.defaultOptions,{allowTraversingTree:!1,animationLimit:250,borderRadius:0,showInLegend:!1,marker:void 0,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return G(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,traverseUpButton:{position:{align:"right",
x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",brightness:z?0:.1,halo:!1,opacity:.75,shadow:!1}}});return b}(r);D(u.prototype,{buildKDTree:a,colorKey:"colorValue",directTouch:!0,drawLegendSymbol:q.drawRectangle,getExtremesFromAll:!0,getSymbol:a,optionalAxis:"colorAxis",parallelArrays:["x","y","value","colorValue"],pointArrayMap:["value"],pointClass:w,trackerGroups:["group","dataLabelsGroup"],utils:{recursive:f.recursive}});g.registerSeriesType("treemap",
u);"";return u});v(a,"masters/modules/treemap.src.js",[a["Core/Globals.js"],a["Extensions/Breadcrumbs.js"]],function(a,h){a.Breadcrumbs=h})});
//# sourceMappingURL=treemap.js.map